In [418]:
"""generate_data.py -- deterministic synthetic data for the Instamart Customer Intelligence capstone.
Run:  python generate_data.py        (writes ./data/raw/*.csv and ./data/policies/*.txt)
Uses only the Python standard library. All data is synthetic and fictional."""
import csv, math, os, random
from datetime import datetime, timedelta

rng = random.Random(42)
RAW, POL = os.path.join("data", "raw"), os.path.join("data", "policies")
os.makedirs(RAW, exist_ok=True); os.makedirs(POL, exist_ok=True)

CITIES = ["Chennai", "Mumbai", "Bengaluru", "Delhi", "Hyderabad", "Pune"]
PRODUCTS = [  # (name, category, price_inr)
    ("Basmati Rice 1kg", "Grocery", 129), ("Toor Dal 1kg", "Grocery", 165), ("Atta 5kg", "Grocery", 245),
    ("Sunflower Oil 1L", "Grocery", 155), ("Sugar 1kg", "Grocery", 48), ("Salt 1kg", "Grocery", 24),
    ("Tea Powder 250g", "Grocery", 120), ("Poha 500g", "Grocery", 42),
    ("Toned Milk 500ml", "Dairy", 29), ("Curd 400g", "Dairy", 45), ("Paneer 200g", "Dairy", 95),
    ("Butter 100g", "Dairy", 58), ("Cheese Slices 200g", "Dairy", 130), ("Ghee 500ml", "Dairy", 340),
    ("Eggs 12 Pack", "Dairy", 84), ("Lassi 200ml", "Dairy", 25),
    ("Potato Chips 52g", "Snacks", 20), ("Namkeen 200g", "Snacks", 60), ("Biscuits 150g", "Snacks", 30),
    ("Dark Chocolate 80g", "Snacks", 150), ("Instant Noodles 4 Pack", "Snacks", 56), ("Popcorn 100g", "Snacks", 45),
    ("Peanut Butter 340g", "Snacks", 210), ("Cold Coffee Can 180ml", "Snacks", 90),
    ("Shampoo 340ml", "Personal Care", 280), ("Face Wash 100ml", "Personal Care", 190),
    ("Toothpaste 150g", "Personal Care", 98), ("Soap 4 Pack", "Personal Care", 150),
    ("Hand Wash 250ml", "Personal Care", 99), ("Body Lotion 400ml", "Personal Care", 350),
    ("Deodorant 150ml", "Personal Care", 220), ("Sunscreen 50g", "Personal Care", 399),
    ("Wireless Earbuds", "Electronics", 1499), ("Power Bank 10000mAh", "Electronics", 1299),
    ("USB-C Cable 1m", "Electronics", 299), ("Phone Charger 20W", "Electronics", 799),
    ("Smart Bulb", "Electronics", 599), ("Bluetooth Speaker", "Electronics", 1999),
    ("Phone Stand", "Electronics", 349), ("Memory Card 64GB", "Electronics", 549)]
CAT_IDX = {}
for i, (_, c, _) in enumerate(PRODUCTS):
    CAT_IDX.setdefault(c, []).append(i)

def write(name, header, rows):
    with open(os.path.join(RAW, name), "w", newline="", encoding="utf-8") as f:
        w = csv.writer(f); w.writerow(header); w.writerows(rows)

def poisson(lam):
    L, k, p = math.exp(-lam), 0, 1.0
    while True:
        p *= rng.random()
        if p <= L:
            return k
        k += 1

def mangle_city(c):
    r = rng.random()
    return c.lower() if r < .20 else c.upper() if r < .32 else (" " + c + " ") if r < .42 else c

def mangle_gender(g):
    opts = {"male": ["male", "Male", "M", "m", "MALE"], "female": ["female", "Female", "F", "f", "FEMALE"]}[g]
    return rng.choice(opts)

# ---------------- products ----------------
write("products.csv", ["product_id", "product_name", "category", "price_inr"],
      [[f"P{i+1:03d}", n, c, p] for i, (n, c, p) in enumerate(PRODUCTS)])

# ---------------- customers ----------------
N_CUST = 1200
IMPOSSIBLE_AGE = {10: 280, 110: -4, 210: 0, 310: 150, 410: 999, 510: 200}
cust, arche = [], {}
for i in range(N_CUST):
    cid = f"C{i+1:04d}"
    r = rng.random()
    arche[cid] = "premium" if r < .20 else "frequent" if r < .60 else "rare"
    signup = datetime(2024, 1, 1) + timedelta(days=rng.randint(0, 455))
    age = IMPOSSIBLE_AGE.get(i, rng.randint(18, 60))
    age = "" if (i not in IMPOSSIBLE_AGE and rng.random() < .05) else age
    gender = "" if rng.random() < .03 else mangle_gender(rng.choice(["male", "female"]))
    cust.append([cid, mangle_city(rng.choice(CITIES)), signup.strftime("%Y-%m-%d"), age, gender])
write("customers.csv", ["customer_id", "city", "signup_date", "age", "gender"], cust)

# ---------------- orders ----------------
WIN_START, WIN_DAYS = datetime(2025, 4, 1), 183          # 2025-04-01 .. 2025-09-30
RATE = {"premium": 1.0, "frequent": 3.5, "rare": 0.5}   # expected orders per month
def pick_product(a):
    if a == "premium":
        pool = CAT_IDX["Electronics"] if rng.random() < .7 else CAT_IDX["Personal Care"] + CAT_IDX["Snacks"]
        return rng.choice(pool), rng.randint(1, 2)
    if a == "frequent":
        return rng.choice(CAT_IDX["Grocery"] + CAT_IDX["Dairy"] + CAT_IDX["Snacks"]), rng.randint(1, 3)
    return rng.choice(CAT_IDX["Grocery"] + CAT_IDX["Dairy"] + CAT_IDX["Snacks"] + CAT_IDX["Personal Care"]), rng.randint(1, 2)

rows, oid = [], 100000
for cid, a in arche.items():
    for _ in range(poisson(RATE[a] * 6.0)):
        oid += 1
        pi, qty = pick_product(a)
        ts = WIN_START + timedelta(days=rng.randint(0, WIN_DAYS - 1), hours=rng.randint(7, 22),
                                   minutes=rng.randint(0, 59), seconds=rng.randint(0, 59))
        disc = rng.choice([0, 0, 0, 5, 10, 15, 20, 25, 40])
        status = "cancelled" if rng.random() < .10 else "completed"
        amount = round(PRODUCTS[pi][2] * qty * (1 - disc / 100), 2)
        if status == "cancelled":
            deliv = ""
        else:
            deliv = rng.randint(46, 75) if rng.random() < .10 else max(8, min(45, int(round(rng.gauss(24, 8)))))
            if rng.random() < .06:
                deliv = ""
        rows.append({"order_id": f"ORD-{oid}", "customer_id": cid, "product_id": f"P{pi+1:03d}", "quantity": qty,
                     "order_ts": ts, "status": status, "discount_pct": disc, "order_amount": amount,
                     "delivery_minutes": deliv})
out = []
for k, r in enumerate(rows):
    if k % 100 == 7 and r["status"] == "completed" and r["delivery_minutes"] != "":
        r["delivery_minutes"] = -10                          # impossible negative duration (planted)
    if r["status"] == "completed" and rng.random() < .01:
        r["order_amount"] = "N/A" if rng.random() < .5 else "error"   # unparseable amount (planted)
    base = [r["order_id"], r["customer_id"], r["product_id"], r["quantity"], r["order_ts"].strftime("%Y-%m-%d %H:%M:%S"),
            r["status"], r["discount_pct"], r["order_amount"], r["delivery_minutes"]]
    out.append(base)
    if rng.random() < .05:   # earlier 'pending' record of the same order (partial duplicate)
        early = list(base); early[4] = (r["order_ts"] - timedelta(minutes=rng.randint(1, 10))).strftime("%Y-%m-%d %H:%M:%S")
        early[5] = "pending"; early[8] = ""
        out.append(early)
    if rng.random() < .01:   # exact duplicate
        out.append(list(base))
rng.shuffle(out)
write("orders.csv", ["order_id", "customer_id", "product_id", "quantity", "order_ts", "status",
                     "discount_pct", "order_amount", "delivery_minutes"], out)

# ---------------- support tickets ----------------
T = {"billing": ["I was charged twice for order {o}. Please refund the extra payment. My email is {e}.",
                 "The invoice for {o} shows a wrong amount. Call me on {p} to correct the bill.",
                 "Extra money was deducted for order {o}, please check the bill. Contact {e}."],
     "delivery": ["My order {o} has not arrived and the rider is not picking up calls. Please call {p}.",
                  "Delivery for {o} is very late, it was promised in 20 minutes. Write to {e}.",
                  "The rider marked {o} as delivered but I never received the package. Call {p}."],
     "technical": ["The app crashes every time I open the cart. I tried to place {o} again and got an error. Email {e}.",
                   "I cannot login, the OTP never arrives on {p}.",
                   "The payment page shows an error and the app freezes when I apply a coupon. Order {o}."],
     "fraud": ["There is an unauthorized transaction on my card linked to order {o}. I did not place it. Call {p}.",
               "Someone hacked my account and used my wallet balance. This is fraud, contact {e}.",
               "I was charged for order {o} that I never made, it looks like fraud on my account. Call {p}."]}
order_by_cust = {}
for r in out:
    order_by_cust.setdefault(r[1], r[0])
cust_with_orders = sorted(order_by_cust)
tickets = []
cats = list(T)
for n in range(1, 157):
    cat = cats[(n - 1) % 4]
    cid = rng.choice(cust_with_orders)
    txt = rng.choice(T[cat]).format(o=order_by_cust[cid], e=f"user{n}@example.com", p=str(rng.choice("6789")) + "".join(rng.choice("0123456789") for _ in range(9)))
    tickets.append([f"T{n:04d}", cid, order_by_cust[cid], txt, cat])
FILL = "The same problem keeps happening and nobody has given me a clear answer yet. "
for n in range(157, 161):                         # 4 empty tickets
    tickets.append([f"T{n:04d}", rng.choice(cust_with_orders), "", "", "none"])
for n in range(161, 165):                         # 4 very long tickets (~520 words)
    tickets.append([f"T{n:04d}", rng.choice(cust_with_orders), "", ("My delivery was late. " + FILL * 40).strip(), "delivery"])
rng.shuffle(tickets)
write("tickets.csv", ["ticket_id", "customer_id", "order_id", "text", "true_category"], tickets)

# ---------------- policy documents ----------------
DOCS = {
"refund_policy.txt": """Refund Policy. A refund can be requested only for orders whose status is completed. Orders with status cancelled were never charged, so no refund applies to them. If a completed order is delivered in more than 45 minutes, the customer receives a full refund of the order amount. If a completed order is delivered in 45 minutes or less, no late-delivery refund is paid. Refunds up to INR 1000 are approved automatically by the support system. A refund above INR 1000 must be approved by a human support lead before money is returned. Approved refunds are credited to the original payment method within 5 working days. A refund request must be raised within 7 days of the delivery date.""",
"delivery_policy.txt": """Delivery Policy. Standard delivery is promised within 30 minutes of order confirmation in all supported cities. The supported cities are Chennai, Mumbai, Bengaluru, Delhi, Hyderabad and Pune. A delivery fee of INR 25 is charged on orders below INR 199, and delivery is free on orders of INR 199 or more. During heavy rain the promised time may extend to 60 minutes and the app shows a rain notice. A rider will attempt to contact the customer twice before marking an order as undeliverable. Electronics items are delivered only after the customer shares a one time password with the rider.""",
"payment_policy.txt": """Payment Policy. Customers can pay using UPI, debit card, credit card or cash on delivery. Cash on delivery is available only for orders up to INR 2500. If a payment fails but money is deducted, the amount is returned automatically within 48 hours. A customer who sees two charges for one order should raise a billing ticket with the order identifier. Wallet balance can be used for any order and is never refunded as cash. Coupons cannot be combined with wallet balance on the same order.""",
"privacy_policy.txt": """Privacy Policy. Customer phone numbers and email addresses are used only for order updates and support. Support tickets are processed with personal details masked before any automated tool reads them. Delivery addresses are deleted from active systems 180 days after the last order. A customer can ask for account deletion and the request is completed within 30 days. Payment card numbers are never stored by the support system.""",
"escalation_policy.txt": """Escalation Policy. A ticket about fraud or an unauthorized transaction is marked high priority and sent to the security team within 2 hours. Tickets from premium customers are answered within 1 hour, and all other tickets within 24 hours. If an automated assistant cannot resolve a ticket within 6 steps, it must hand the case to a human agent with a short summary. A human agent must call the customer back if such a high-value request is rejected."""}
for fn, body in DOCS.items():
    with open(os.path.join(POL, fn), "w", encoding="utf-8") as f:
        f.write(body + "\n")

# ---------------- policy evaluation questions ----------------
QA = [("What delivery time makes a completed order eligible for a full refund?", "refund_policy.txt", "more than 45 minutes"),
      ("Who must approve a refund above INR 1000?", "refund_policy.txt", "human support lead"),
      ("How many days do I have to raise a refund request?", "refund_policy.txt", "within 7 days"),
      ("What is the delivery fee on small orders?", "delivery_policy.txt", "INR 25"),
      ("On orders of what value is delivery free?", "delivery_policy.txt", "INR 199 or more"),
      ("Why does the electronics delivery need a one time password?", "delivery_policy.txt", "one time password"),
      ("Is cash on delivery available for a large order?", "payment_policy.txt", "INR 2500"),
      ("How soon is money returned when a payment fails but is deducted?", "payment_policy.txt", "48 hours"),
      ("Can wallet balance be refunded as cash?", "payment_policy.txt", "never refunded as cash"),
      ("When are delivery addresses deleted from active systems?", "privacy_policy.txt", "180 days"),
      ("How fast must a fraud ticket reach the security team?", "escalation_policy.txt", "within 2 hours"),
      ("After how many steps must an automated assistant hand over to a human?", "escalation_policy.txt", "6 steps"),
      ("What is the favourite colour of the company mascot?", "NONE", ""),
      ("Who won the cricket world cup final?", "NONE", "")]
with open(os.path.join(RAW, "policy_eval.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f); w.writerow(["question", "expected_doc", "expected_fact"]); w.writerows(QA)

# ---------------- agent scenarios (simulated refund requests) ----------------
from collections import Counter
cnt = Counter(r[0] for r in out)
def clean_row(r):                                    # single-record, fully valid order
    try:
        return cnt[r[0]] == 1 and r[5] in ("completed", "cancelled") and float(r[7]) > 0 and \
            (r[5] == "cancelled" or (r[8] != "" and 8 <= int(r[8]) <= 75))
    except ValueError:
        return False
ok_rows = sorted((r for r in out if clean_row(r)), key=lambda r: r[0])
def first(pred):
    return next(r for r in ok_rows if pred(r))
late_small = [r for r in ok_rows if r[5] == "completed" and int(r[8]) > 45 and float(r[7]) <= 1000][:2]
late_big = first(lambda r: r[5] == "completed" and int(r[8]) > 45 and float(r[7]) > 1000)
on_time = first(lambda r: r[5] == "completed" and int(r[8]) <= 45)
cancelled = first(lambda r: r[5] == "cancelled")
SC = []
for r in late_small:
    SC.append((r[1], f"My order {r[0]} reached me very late. I would like a refund.", "REFUND", float(r[7])))
SC.append((late_big[1], f"Order {late_big[0]} arrived far too late, please refund me.", "ESCALATE", float(late_big[7])))
SC.append((on_time[1], f"Please refund order {on_time[0]}, I did not like the delivery.", "DENIED", 0))
SC.append((cancelled[1], f"I want my money back for order {cancelled[0]}.", "DENIED", 0))
SC.append(("C0001", "Refund for order ORD-999999 please.", "NOT_FOUND", 0))
SC.append((late_small[0][1], f"[LOOP] Refund order {late_small[0][0]}.", "FALLBACK", 0))
with open(os.path.join(RAW, "agent_scenarios.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f); w.writerow(["scenario_id", "customer_id", "message", "expected_outcome", "expected_refund_inr"])
    for i, (cid, msg, oc, amt) in enumerate(SC, 1):
        w.writerow([f"S{i}", cid, msg, oc, f"{amt:.2f}"])
print("generated: customers=%d products=%d orders_raw=%d tickets=%d" % (len(cust), len(PRODUCTS), len(out), len(tickets)))

generated: customers=1200 products=40 orders_raw=13084 tickets=164

In [419]:
!python generate_data.py

In [420]:
import os

for folder in ["data/raw", "data/policies"]:
    print("\n---", folder, "---")
    for file in sorted(os.listdir(folder)):
        path = os.path.join(folder, file)
        print(file, "-", os.path.getsize(path), "bytes")

--- data/raw ---
agent_scenarios.csv - 601 bytes
customers.csv - 39704 bytes
orders.csv - 860846 bytes
policy_eval.csv - 1198 bytes
products.csv - 1403 bytes
tickets.csv - 32857 bytes

--- data/policies ---
delivery_policy.txt - 590 bytes
escalation_policy.txt - 450 bytes
payment_policy.txt - 489 bytes
privacy_policy.txt - 429 bytes
refund_policy.txt - 685 bytes

In [421]:
import pandas as pd
import os

for file in sorted(os.listdir("data/raw")):
    if file.endswith(".csv"):
        path = os.path.join("data/raw", file)
        df = pd.read_csv(path)

        print("\nFile:", file)
        print("Rows:", len(df))
        print("Columns:", list(df.columns))
        print(df.head(2))

File: agent_scenarios.csv
Rows: 7
Columns: ['scenario_id', 'customer_id', 'message', 'expected_outcome', 'expected_refund_inr']
  scenario_id customer_id                                            message  \
0          S1       C0007  My order ORD-100048 reached me very late. I wo...
1          S2       C0008  My order ORD-100067 reached me very late. I wo...

  expected_outcome  expected_refund_inr
0           REFUND               128.25
1           REFUND               135.00

File: customers.csv
Rows: 1200
Columns: ['customer_id', 'city', 'signup_date', 'age', 'gender']
  customer_id     city signup_date   age gender
0       C0001  Chennai  2024-01-13  35.0   MALE
1       C0002    DELHI  2024-02-17  31.0   MALE

File: orders.csv
Rows: 13084
Columns: ['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes']
     order_id customer_id product_id  quantity             order_ts  \
0  ORD-108250       C0792       P004         2  2025-09-01 12:24:59
1  ORD-101939       C0190       P003         1  2025-08-17 07:07:23

      status  discount_pct order_amount  delivery_minutes
0  completed             0        310.0              17.0
1  completed             5       232.75              21.0

File: policy_eval.csv
Rows: 14
Columns: ['question', 'expected_doc', 'expected_fact']
                                            question       expected_doc  \
0  What delivery time makes a completed order eli...  refund_policy.txt
1          Who must approve a refund above INR 1000?  refund_policy.txt

          expected_fact
0  more than 45 minutes
1    human support lead

File: products.csv
Rows: 40
Columns: ['product_id', 'product_name', 'category', 'price_inr']
  product_id      product_name category  price_inr
0       P001  Basmati Rice 1kg  Grocery        129
1       P002      Toor Dal 1kg  Grocery        165

File: tickets.csv
Rows: 164
Columns: ['ticket_id', 'customer_id', 'order_id', 'text', 'true_category']
  ticket_id customer_id    order_id  \
0     T0024       C0486  ORD-105035
1     T0073       C0080  ORD-100816

                                                text true_category
0  There is an unauthorized transaction on my car...         fraud
1  The invoice for ORD-100816 shows a wrong amoun...       billing

**Data cleaning**

In [422]:
import pandas as pd
import os

# Folders
RAW = "data/raw"
CLEAN = "data/processed/cleaned"

os.makedirs(CLEAN, exist_ok=True)

# Read all CSV files
customers = pd.read_csv(f"{RAW}/customers.csv")
products = pd.read_csv(f"{RAW}/products.csv")
orders = pd.read_csv(f"{RAW}/orders.csv")
tickets = pd.read_csv(f"{RAW}/tickets.csv")

# 1. Clean customers
customers = customers.drop_duplicates(subset=["customer_id"])
customers["city"] = customers["city"].astype("string").str.strip().str.title()
customers["age"] = pd.to_numeric(customers["age"], errors="coerce")
customers.loc[~customers["age"].between(18, 100), "age"] = pd.NA
customers["gender"] = customers["gender"].astype("string").str.strip().str.lower()
customers["gender"] = customers["gender"].replace({
    "m": "male",
    "f": "female",
    "": pd.NA
})
customers.loc[~customers["gender"].isin(["male", "female"]), "gender"] = pd.NA

# 2. Clean products
products = products.drop_duplicates(subset=["product_id"])
products["product_name"] = products["product_name"].astype("string").str.strip()
products["category"] = products["category"].astype("string").str.strip()
products["price_inr"] = pd.to_numeric(products["price_inr"], errors="coerce")

# 3. Clean orders
orders = orders.drop_duplicates()
orders["order_ts"] = pd.to_datetime(orders["order_ts"], errors="coerce")
orders["quantity"] = pd.to_numeric(orders["quantity"], errors="coerce")
orders["discount_pct"] = pd.to_numeric(orders["discount_pct"], errors="coerce")
orders["order_amount"] = pd.to_numeric(orders["order_amount"], errors="coerce")
orders["delivery_minutes"] = pd.to_numeric(
    orders["delivery_minutes"], errors="coerce"
)

orders.loc[~orders["quantity"].between(1, 100), "quantity"] = pd.NA
orders.loc[~orders["discount_pct"].between(0, 100), "discount_pct"] = pd.NA
orders.loc[orders["order_amount"] <= 0, "order_amount"] = pd.NA
orders.loc[orders["delivery_minutes"] < 0, "delivery_minutes"] = pd.NA

# Keep the latest status record for each order ID
orders = orders.sort_values("order_ts")
orders = orders.drop_duplicates(subset=["order_id"], keep="last")

# 4. Clean support tickets
tickets = tickets.drop_duplicates(subset=["ticket_id"])
tickets["text"] = tickets["text"].fillna("").astype(str).str.strip()
tickets["true_category"] = tickets["true_category"].astype("string").str.strip().str.lower()

# Save cleaned data
cleaned_data = {
    "customers": customers,
    "products": products,
    "orders": orders,
    "tickets": tickets
}

for name, df in cleaned_data.items():
    output_path = f"{CLEAN}/{name}.csv"
    df.to_csv(output_path, index=False)
    print(f"{name}: {len(df)} rows saved")

print("\nData cleaning completed!")

customers: 1200 rows saved
products: 40 rows saved
orders: 12309 rows saved
tickets: 164 rows saved

Data cleaning completed!

**Database**

In [423]:
import os
import sqlite3
import pandas as pd

# Database folder
os.makedirs("data/processed", exist_ok=True)

# Connect to SQLite database
db_path = "data/processed/instamart.db"
conn = sqlite3.connect(db_path)

# Load cleaned CSV files into database
cleaned_folder = "data/processed/cleaned"

for file in os.listdir(cleaned_folder):
    if file.endswith(".csv"):
        table_name = file.replace(".csv", "")
        df = pd.read_csv(os.path.join(cleaned_folder, file))

        df.to_sql(
            table_name,
            conn,
            if_exists="replace",
            index=False
        )

        print(f"Table created: {table_name} | Rows: {len(df)}")

conn.close()

print("\nSQLite database created successfully!")

Table created: tickets | Rows: 164
Table created: products | Rows: 40
Table created: customers | Rows: 1200
Table created: orders | Rows: 12309

SQLite database created successfully!

**Database** **tables**

In [424]:
import os
import sqlite3
import pandas as pd

# Check cleaned CSV folder
folder = "data/processed/cleaned"

print("Cleaned folder exists:", os.path.exists(folder))

if not os.path.exists(folder):
    raise FileNotFoundError(
        "Cleaned CSV folder not found. Please run the Data Cleaning code first."
    )

files = [f for f in os.listdir(folder) if f.endswith(".csv")]
print("CSV files found:", files)

if not files:
    raise FileNotFoundError(
        "No CSV files found. Please run the Data Cleaning code first."
    )

# Create tables in SQLite
db_path = "data/processed/instamart.db"
conn = sqlite3.connect(db_path)

for file in files:
    table_name = os.path.splitext(file)[0]
    csv_path = os.path.join(folder, file)

    df = pd.read_csv(csv_path)

    df.to_sql(
        table_name,
        conn,
        if_exists="replace",
        index=False
    )

    print(f"Created table: {table_name} | Rows: {len(df)}")

conn.close()

print("\nDatabase tables created successfully!")

Cleaned folder exists: True
CSV files found: ['tickets.csv', 'products.csv', 'customers.csv', 'orders.csv']
Created table: tickets | Rows: 164
Created table: products | Rows: 40
Created table: customers | Rows: 1200
Created table: orders | Rows: 12309

Database tables created successfully!

In [425]:
import sqlite3

conn = sqlite3.connect("data/processed/instamart.db")

tables = conn.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name;
""").fetchall()

print("Tables found:")
for table in tables:
    print(table[0])

conn.close()

Tables found:
customers
orders
products
tickets

**Fisrt SQL Query**

In [426]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("data/processed/instamart.db")

query = """
SELECT
    city,
    COUNT(*) AS total_customers
FROM customers
GROUP BY city
ORDER BY total_customers DESC;
"""

result = pd.read_sql_query(query, conn)
display(result)

conn.close()

        city  total_customers
0       Pune              227
1      Delhi              210
2  Bengaluru              197
3  Hyderabad              191
4    Chennai              191
5     Mumbai              184

**Customer** **Segmentation**

In [427]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("data/processed/instamart.db")

query = """
SELECT
    c.customer_id,
    c.city,
    COUNT(DISTINCT CASE
        WHEN o.status = 'completed' THEN o.order_id
    END) AS total_orders,
    COALESCE(SUM(
        CASE WHEN o.status = 'completed'
        THEN o.order_amount ELSE 0 END
    ), 0) AS total_spend
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.city
"""

customers_df = pd.read_sql_query(query, conn)

def assign_segment(row):
    if row["total_orders"] >= 15 and row["total_spend"] >= 5000:
        return "Premium"
    elif row["total_orders"] >= 5:
        return "Frequent"
    else:
        return "Rare"

customers_df["customer_segment"] = customers_df.apply(
    assign_segment, axis=1
)

print("Customer Segmentation Results:")
display(customers_df.head(10))

print("\nSegment Summary:")
display(
    customers_df["customer_segment"]
    .value_counts()
    .rename_axis("Segment")
    .reset_index(name="Customer Count")
)

conn.close()

Customer Segmentation Results:

  customer_id       city  total_orders  total_spend customer_segment
0       C0001    Chennai             4       487.65             Rare
1       C0002      Delhi             7      4644.90         Frequent
2       C0003  Bengaluru            22      3644.85         Frequent
3       C0004  Bengaluru             5       369.00         Frequent
4       C0005  Bengaluru             2       324.00             Rare
5       C0006    Chennai             1        90.00             Rare
6       C0007  Hyderabad            18      2600.00         Frequent
7       C0008    Chennai            15      3096.50         Frequent
8       C0009       Pune            11      8424.80         Frequent
9       C0010      Delhi             4       450.00             Rare

Segment Summary:

    Segment  Customer Count
0  Frequent             640
1      Rare             537
2   Premium              23

**Customer Lapse Prediction**

In [428]:
import pandas as pd
import sqlite3

conn = sqlite3.connect("data/processed/instamart.db")

query = """
SELECT
    c.customer_id,
    c.city,
    MAX(
        CASE
            WHEN o.status = 'completed'
            THEN o.order_ts
        END
    ) AS last_order_date,
    COUNT(
        DISTINCT CASE
            WHEN o.status = 'completed'
            THEN o.order_id
        END
    ) AS total_orders
FROM customers c
LEFT JOIN orders o
    ON c.customer_id = o.customer_id
GROUP BY c.customer_id, c.city
"""

df = pd.read_sql_query(query, conn)
conn.close()

# Convert order date into datetime
df["last_order_date"] = pd.to_datetime(
    df["last_order_date"], errors="coerce"
)

# Calculate days since last order
reference_date = pd.Timestamp.now().normalize()

df["days_since_last_order"] = (
    reference_date - df["last_order_date"]
).dt.days

# Identify customers at risk
df["lapse_status"] = df["days_since_last_order"].apply(
    lambda days: (
        "No Completed Orders" if pd.isna(days)
        else "At Risk" if days > 30
        else "Active"
    )
)

print("Customer Lapse Analysis")
display(df.head(10))

print("\nLapse Summary")
display(
    df["lapse_status"]
    .value_counts()
    .rename_axis("Status")
    .reset_index(name="Customer Count")
)

# Save results
import os
os.makedirs("outputs", exist_ok=True)

df.to_csv("outputs/customer_lapse_analysis.csv", index=False)

print("\nSaved: outputs/customer_lapse_analysis.csv")

Customer Lapse Analysis

,customer_id,city,last_order_date,total_orders,days_since_last_order,lapse_status
0,C0001,Chennai,2025-09-16 08:07:21,4,408.0,At Risk
1,C0002,Delhi,2025-09-02 13:33:13,7,422.0,At Risk
2,C0003,Bengaluru,2025-09-23 16:55:36,22,401.0,At Risk
3,C0004,Bengaluru,2025-09-30 15:09:46,5,394.0,At Risk
4,C0005,Bengaluru,2025-05-06 21:44:20,2,541.0,At Risk
5,C0006,Chennai,2025-08-27 18:08:39,1,428.0,At Risk
6,C0007,Hyderabad,2025-09-27 13:30:30,18,397.0,At Risk
7,C0008,Chennai,2025-09-27 20:35:08,15,397.0,At Risk
8,C0009,Pune,2025-09-11 13:26:03,11,413.0,At Risk
9,C0010,Delhi,2025-07-26 07:10:07,4,460.0,At Risk

Lapse Summary

                Status  Customer Count
0              At Risk            1175
1  No Completed Orders              25

Saved: outputs/customer_lapse_analysis.csv

**Support Ticket Classificaion**

In [429]:
import pandas as pd
import os

# Load ticket data
tickets = pd.read_csv("data/raw/tickets.csv")

print("Total tickets:", len(tickets))
print("\nAvailable columns:")
print(tickets.columns.tolist())

display(tickets.head(5))

Total tickets: 164

Available columns:
['ticket_id', 'customer_id', 'order_id', 'text', 'true_category']

,ticket_id,customer_id,order_id,text,true_category
0,T0024,C0486,ORD-105035,There is an unauthorized transaction on my car...,fraud
1,T0073,C0080,ORD-100816,The invoice for ORD-100816 shows a wrong amoun...,billing
2,T0095,C1087,ORD-111156,The payment page shows an error and the app fr...,technical
3,T0159,C1172,NaN,NaN,none
4,T0080,C0910,ORD-109516,I was charged for order ORD-109516 that I neve...,fraud

**Ticket Classification + Missing Data Cleaning**

In [430]:
import pandas as pd
import os

# Load tickets
tickets = pd.read_csv("data/raw/tickets.csv")

# Clean missing values
tickets["text"] = tickets["text"].fillna("").astype(str).str.strip()
tickets["true_category"] = (
    tickets["true_category"].fillna("none").astype(str).str.strip()
)

# Simple rule-based classification
def classify_ticket(text):
    text = text.lower()

    if any(word in text for word in ["fraud", "unauthorized", "charged for order"]):
        return "fraud"
    elif any(word in text for word in ["refund", "money back", "reimbursement"]):
        return "refund"
    elif any(word in text for word in ["delivery", "delivered", "late order"]):
        return "delivery"
    elif any(word in text for word in ["payment", "transaction", "invoice", "billing", "amount"]):
        return "billing"
    elif any(word in text for word in ["broken", "damaged", "wrong item", "missing item"]):
        return "product"
    elif any(word in text for word in ["error", "crash", "app freezes", "technical"]):
        return "technical"
    elif text == "":
        return "none"
    else:
        return "other"

tickets["predicted_category"] = tickets["text"].apply(classify_ticket)

# Save results
os.makedirs("outputs", exist_ok=True)
tickets.to_csv("outputs/classified_tickets.csv", index=False)

print("Total tickets:", len(tickets))
print("\nPredicted category counts:")
display(
    tickets["predicted_category"]
    .value_counts()
    .rename_axis("Category")
    .reset_index(name="Count")
)

print("\nSample results:")
display(tickets[["ticket_id", "text", "true_category", "predicted_category"]].head(10))

print("\nSaved: outputs/classified_tickets.csv")

Total tickets: 164

Predicted category counts:

    Category  Count
0      other     43
1      fraud     39
2   delivery     31
3    billing     26
4  technical     12
5     refund      9
6       none      4

Sample results:

,ticket_id,text,true_category,predicted_category
0,T0024,There is an unauthorized transaction on my car...,fraud,fraud
1,T0073,The invoice for ORD-100816 shows a wrong amoun...,billing,billing
2,T0095,The payment page shows an error and the app fr...,technical,billing
3,T0159,,none,none
4,T0080,I was charged for order ORD-109516 that I neve...,fraud,fraud
5,T0124,I was charged for order ORD-101417 that I neve...,fraud,fraud
6,T0061,"Extra money was deducted for order ORD-108532,...",billing,other
7,T0118,"Delivery for ORD-103823 is very late, it was p...",delivery,delivery
8,T0037,I was charged twice for order ORD-111925. Plea...,billing,refund
9,T0002,The rider marked ORD-109184 as delivered but I...,delivery,delivery

Saved: outputs/classified_tickets.csv

**Privacy Guardrails**

In [431]:
import pandas as pd
import re
import os

# Load original ticket data directly
tickets = pd.read_csv("data/raw/tickets.csv")

# Handle missing text
tickets["text"] = tickets["text"].fillna("").astype(str)

# Mask email and phone numbers
def mask_personal_info(text):
    text = re.sub(
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
        '[EMAIL_MASKED]',
        text
    )

    text = re.sub(
        r'(?<!\d)(?:\+91[\s-]?)?[6-9]\d{9}(?!\d)',
        '[PHONE_MASKED]',
        text
    )

    return text

tickets["masked_text"] = tickets["text"].apply(mask_personal_info)

# Save output
os.makedirs("outputs", exist_ok=True)
tickets.to_csv("outputs/privacy_protected_tickets.csv", index=False)

print("Privacy masking completed!")
print("Total tickets:", len(tickets))

display(tickets[["ticket_id", "text", "masked_text"]].head(10))

print("Saved successfully: outputs/privacy_protected_tickets.csv")

Privacy masking completed!
Total tickets: 164

,ticket_id,text,masked_text
0,T0024,There is an unauthorized transaction on my car...,There is an unauthorized transaction on my car...
1,T0073,The invoice for ORD-100816 shows a wrong amoun...,The invoice for ORD-100816 shows a wrong amoun...
2,T0095,The payment page shows an error and the app fr...,The payment page shows an error and the app fr...
3,T0159,,
4,T0080,I was charged for order ORD-109516 that I neve...,I was charged for order ORD-109516 that I neve...
5,T0124,I was charged for order ORD-101417 that I neve...,I was charged for order ORD-101417 that I neve...
6,T0061,"Extra money was deducted for order ORD-108532,...","Extra money was deducted for order ORD-108532,..."
7,T0118,"Delivery for ORD-103823 is very late, it was p...","Delivery for ORD-103823 is very late, it was p..."
8,T0037,I was charged twice for order ORD-111925. Plea...,I was charged twice for order ORD-111925. Plea...
9,T0002,The rider marked ORD-109184 as delivered but I...,The rider marked ORD-109184 as delivered but I...

Saved successfully: outputs/privacy_protected_tickets.csv

**Policy RAG**

In [432]:
import os

policy_folder = "data/policies"

print("Policy files:")

for file in os.listdir(policy_folder):
    print(file)

Policy files:
delivery_policy.txt
privacy_policy.txt
refund_policy.txt
escalation_policy.txt
payment_policy.txt

In [433]:
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

print("Total Orders:", len(orders))
print("Columns:", orders.columns.tolist())

display(orders.head(10))

Total Orders: 13084
Columns: ['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes']

,order_id,customer_id,product_id,quantity,order_ts,status,discount_pct,order_amount,delivery_minutes
0,ORD-108250,C0792,P004,2,2025-09-01 12:24:59,completed,0,310.0,17.0
1,ORD-101939,C0190,P003,1,2025-08-17 07:07:23,completed,5,232.75,21.0
2,ORD-108765,C0841,P033,1,2025-07-13 09:42:32,completed,10,1349.1,27.0
3,ORD-108861,C0852,P010,1,2025-07-04 11:23:24,completed,0,45.0,30.0
4,ORD-109150,C0877,P018,2,2025-05-07 15:35:01,completed,20,96.0,28.0
5,ORD-110648,C1033,P021,2,2025-09-07 07:45:45,completed,5,106.4,26.0
6,ORD-109638,C0924,P020,2,2025-08-18 13:09:19,completed,0,300.0,20.0
7,ORD-101535,C0148,P006,3,2025-04-28 21:30:40,completed,5,68.4,31.0
8,ORD-109326,C0896,P022,2,2025-06-04 21:17:27,completed,40,54.0,26.0
9,ORD-110729,C1047,P009,1,2025-08-19 10:05:22,pending,0,29.0,NaN

**Order Analysis**

In [434]:
import pandas as pd

# Load orders data
orders = pd.read_csv("data/raw/orders.csv")

print("Total Orders:", len(orders))
print("\nOrder Columns:")
print(orders.columns.tolist())

# 1. Order status analysis
print("\n1. Orders by Status")

display(
    orders["status"]
    .value_counts(dropna=False)
    .rename_axis("Order Status")
    .reset_index(name="Total Orders")
)

# 2. City-wise order analysis
if "city" in orders.columns:
    print("\n2. Orders by City")
    display(
        orders.groupby("city")
        .size()
        .reset_index(name="Total Orders")
        .sort_values("Total Orders", ascending=False)
    )
else:
    print("\nCity column is not available in orders.csv")

# 3. Save order analysis
import os
os.makedirs("outputs", exist_ok=True)

orders["status"].value_counts(dropna=False).to_csv(
    "outputs/order_status_summary.csv"
)

print("\nSaved: outputs/order_status_summary.csv")

Total Orders: 13084

Order Columns:
['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes']

1. Orders by Status

  Order Status  Total Orders
0    completed         11217
1    cancelled          1211
2      pending           656

City column is not available in orders.csv

Saved: outputs/order_status_summary.csv

In [435]:
import os

policy_folder = "data/policies"

if os.path.exists(policy_folder):
    for file in sorted(os.listdir(policy_folder)):
        print(file)
else:
    print("Policy folder not found!")

delivery_policy.txt
escalation_policy.txt
payment_policy.txt
privacy_policy.txt
refund_policy.txt

In [436]:
import os

print("Current folder:", os.getcwd())
print("\nFiles and folders:")

for item in os.listdir("."):
    print(item)

print("\nSearch for policy files:")

for root, dirs, files in os.walk("."):
    for file in files:
        if "policy" in file.lower():
            print(os.path.join(root, file))

Current folder: /content

Files and folders:
.config
generate_data.py
__pycache__
mock_llm.py
outputs
README.md
data
sample_data

Search for policy files:
./outputs/policy_evaluation_results.csv
./data/raw/policy_eval.csv
./data/policies/delivery_policy.txt
./data/policies/privacy_policy.txt
./data/policies/refund_policy.txt
./data/policies/escalation_policy.txt
./data/policies/payment_policy.txt

**Refund Policy RAG**

In [437]:
import os

policy_folder = "data/policies"

# Read refund policy
refund_path = os.path.join(
    policy_folder,
    "refund_policy.txt"
)

with open(refund_path, "r", encoding="utf-8") as file:
    refund_policy = file.read()

print("===== REFUND POLICY =====")
print(refund_policy)

===== REFUND POLICY =====
Refund Policy. A refund can be requested only for orders whose status is completed. Orders with status cancelled were never charged, so no refund applies to them. If a completed order is delivered in more than 45 minutes, the customer receives a full refund of the order amount. If a completed order is delivered in 45 minutes or less, no late-delivery refund is paid. Refunds up to INR 1000 are approved automatically by the support system. A refund above INR 1000 must be approved by a human support lead before money is returned. Approved refunds are credited to the original payment method within 5 working days. A refund request must be raised within 7 days of the delivery date.

**Policy RAG**

In [438]:
import os
import re

policy_folder = "data/policies"

# Load all policy files
policies = {}

for filename in os.listdir(policy_folder):
    if filename.endswith(".txt"):
        path = os.path.join(policy_folder, filename)

        with open(path, "r", encoding="utf-8") as file:
            policies[filename] = file.read()

print("Loaded policy files:", len(policies))
for filename in policies:
    print("-", filename)


# Search relevant policy using keywords
def search_policy(question):
    question = question.lower()

    keyword_map = {
        "refund_policy.txt": [
            "refund", "money back", "return", "cancel"
        ],
        "delivery_policy.txt": [
            "delivery", "late", "delay", "delivered"
        ],
        "payment_policy.txt": [
            "payment", "charged", "transaction", "billing"
        ],
        "privacy_policy.txt": [
            "privacy", "personal information", "data", "email"
        ],
        "escalation_policy.txt": [
            "escalate", "complaint", "fraud", "unauthorized"
        ]
    }

    matched_files = []

    for filename, keywords in keyword_map.items():
        if any(keyword in question for keyword in keywords):
            if filename in policies:
                matched_files.append(filename)

    if not matched_files:
        return "No matching policy found. Please contact customer support."

    result = ""
    for filename in matched_files:
        result += f"\n--- {filename} ---\n"
        result += policies[filename] + "\n"

    return result


# Test the RAG search
question = "My order is delayed. What is the delivery policy?"
answer = search_policy(question)

print("\nCustomer Question:", question)
print("\nRelevant Policy:")
print(answer)

Loaded policy files: 5
- delivery_policy.txt
- privacy_policy.txt
- refund_policy.txt
- escalation_policy.txt
- payment_policy.txt

Customer Question: My order is delayed. What is the delivery policy?

Relevant Policy:

--- delivery_policy.txt ---
Delivery Policy. Standard delivery is promised within 30 minutes of order confirmation in all supported cities. The supported cities are Chennai, Mumbai, Bengaluru, Delhi, Hyderabad and Pune. A delivery fee of INR 25 is charged on orders below INR 199, and delivery is free on orders of INR 199 or more. During heavy rain the promised time may extend to 60 minutes and the app shows a rain notice. A rider will attempt to contact the customer twice before marking an order as undeliverable. Electronics items are delivered only after the customer shares a one time password with the rider.

In [439]:
%%writefile mock_llm.py
"""Offline mock LLM for the Instamart capstone."""
import json
import math
import re
from types import SimpleNamespace as NS

class TransientLLMError(Exception):
    """Simulated temporary failure."""

_state = {"calls": 0, "ok": 0}

def reset():
    _state["calls"] = 0
    _state["ok"] = 0

CATS = ["billing", "delivery", "technical", "fraud"]

KW = {
    "fraud": {"unauthorized", "fraud", "hacked", "stolen"},
    "billing": {"charged", "invoice", "bill", "refund", "deducted", "payment"},
    "technical": {"app", "crash", "login", "otp", "error", "freezes"},
    "delivery": {"arrived", "rider", "delivery", "delivered", "late"}
}

def est_tokens(text):
    return math.ceil(len((text or "").split()) * 1.3)

def _words(t):
    return set(re.findall(r"[a-z]+", (t or "").lower()))

def _resp(content=None, tool_calls=None, finish="stop", messages=()):
    prompt = sum(
        est_tokens(m.get("content") or json.dumps(m.get("tool_calls", ""), default=str))
        for m in messages
    )
    comp = est_tokens(content or json.dumps(tool_calls or "", default=str))
    msg = NS(
        role="assistant",
        content=content,
        tool_calls=[NS(**tc) for tc in (tool_calls or [])]
    )
    return NS(
        choices=[NS(message=msg, finish_reason=finish)],
        usage=NS(
            prompt_tokens=prompt,
            completion_tokens=comp,
            total_tokens=prompt + comp
        )
    )

def _classify(messages):
    system, user = messages[0]["content"], messages[-1]["content"]
    _state["calls"] += 1

    if _state["calls"] % 9 == 0:
        raise TransientLLMError("503 server busy")

    _state["ok"] += 1
    order = (
        ["fraud", "technical", "billing", "delivery"]
        if "EXAMPLES:" in system
        else ["billing", "fraud", "technical", "delivery"]
    )
    w = _words(user)
    cat = next((c for c in order if KW[c] & w), "technical")

    if _state["ok"] % 13 == 0:
        return _resp(
            f"The customer appears to have a {cat}-related problem.",
            messages=messages
        )

    if _state["ok"] % 17 == 0:
        return _resp(
            json.dumps({"category": "shipping", "reason": "parcel movement"}),
            messages=messages
        )

    return _resp(
        json.dumps({"category": cat, "reason": "keyword match"}),
        messages=messages
    )

STOP = {
    "the", "a", "an", "is", "of", "to", "for", "in", "on", "how",
    "what", "when", "who", "are", "do", "does", "i", "my", "be",
    "can", "after", "from", "it", "or", "and", "at", "by", "which",
    "why", "if", "than", "that"
}

def _stems(t):
    return {
        w[:5] for w in re.findall(r"[a-z]+", (t or "").lower())
        if w not in STOP
    }

def _policy(messages):
    user = messages[-1]["content"]
    m = re.search(r"CONTEXT:\s*(.*?)\s*QUESTION:\s*(.*)", user, re.S)
    context, question = (m.group(1), m.group(2)) if m else ("", user)

    sents = [
        s.strip()
        for s in re.split(
            r"(?<=[.])\s+",
            re.sub(r"\[[^\]]*\.txt\]", " ", context)
        )
        if s.strip()
    ]

    qs = _stems(question)
    df = {q: sum(q in _stems(s) for s in sents) for q in qs}
    best, best_score = None, 0.0

    for s in sents:
        sc = sum(1.0 / df[q] for q in qs & _stems(s))
        if sc > best_score:
            best, best_score = s, sc

    if best is None:
        return _resp(
            "I could not find that information in the policy documents.",
            messages=messages
        )

    return _resp(best, messages=messages)

def _agent(messages, tools):
    user = next(m["content"] for m in messages if m["role"] == "user")
    tool_msgs = [m for m in messages if m["role"] == "tool"]

    def call(n, a):
        return _resp(
            None,
            [{
                "id": f"call_{len(tool_msgs)+1}",
                "name": n,
                "arguments": a
            }],
            "tool_calls",
            messages
        )

    if "[LOOP]" in user:
        return call("search_policy", {"query": "refund policy"})

    if not tool_msgs:
        m = re.search(r"ORD-\d{6}", user)
        if m:
            return call("get_order", {"order_id": m.group(0)})
        return _resp("NEEDS_INFO: please share the order id.", messages=messages)

    last = tool_msgs[-1]
    data = json.loads(last["content"])
    name = last["name"]

    if name == "get_order":
        if "error" in data:
            return _resp("NOT_FOUND: no such order.", messages=messages)
        return call("search_policy", {"query": "refund policy late delivery"})

    order = json.loads(
        next(m for m in tool_msgs if m["name"] == "get_order")["content"]
    )

    if name == "search_policy":
        if order["status"] != "completed":
            return _resp(
                "DENIED: only completed orders can be refunded.",
                messages=messages
            )
        return call(
            "calculate_refund",
            {
                "order_amount": order["order_amount"],
                "delivery_minutes": order["delivery_minutes"]
            }
        )

    if name == "calculate_refund":
        amt = data["refund_inr"]
        if amt == 0:
            return _resp("DENIED: delivery was within 45 minutes.", messages=messages)
        if amt > 1000:
            return call(
                "escalate_to_human",
                {"order_id": order["order_id"], "refund_inr": amt}
            )
        return call(
            "issue_refund",
            {"order_id": order["order_id"], "refund_inr": amt}
        )

    if name == "issue_refund":
        return _resp(f"REFUND: INR {data['refund_inr']} issued.", messages=messages)

    if name == "escalate_to_human":
        return _resp(
            "ESCALATE: refund above INR 1000 sent to a human lead.",
            messages=messages
        )

    return _resp("DENIED: unable to process.", messages=messages)

def chat(messages, tools=None):
    head = messages[0]["content"].upper()

    if "CLASSIFY" in head:
        return _classify(messages)
    if "POLICY ASSISTANT" in head:
        return _policy(messages)
    if "AGENT" in head:
        return _agent(messages, tools)

    raise ValueError(
        "first message must name one of: CLASSIFY, POLICY ASSISTANT, AGENT"
    )

Overwriting mock_llm.py

In [440]:
import os

print("File exists:", os.path.exists("mock_llm.py"))
print("File size:", os.path.getsize("mock_llm.py"), "bytes")

File exists: True
File size: 6304 bytes

In [441]:
import mock_llm

print("Mock LLM imported successfully!")

messages = [
    {"role": "system", "content": "CLASSIFY"},
    {"role": "user", "content": "My payment was charged twice"}
]

response = mock_llm.chat(messages)

print("Response:", response.choices[0].message.content)

Mock LLM imported successfully!
Response: {"category": "billing", "reason": "keyword match"}

**Offline Customer Support Copilot**

In [442]:
import os

file_path = "mock_llm.py"

if os.path.exists(file_path):
    print("mock_llm.py size:", os.path.getsize(file_path), "bytes")

    with open(file_path, "r", encoding="utf-8") as file:
        content = file.read()

    print("\nFirst 40 lines:")
    print("\n".join(content.splitlines()[:40]))
else:
    print("mock_llm.py not found!")

mock_llm.py size: 6304 bytes

First 40 lines:
"""Offline mock LLM for the Instamart capstone."""
import json
import math
import re
from types import SimpleNamespace as NS

class TransientLLMError(Exception):
    """Simulated temporary failure."""

_state = {"calls": 0, "ok": 0}

def reset():
    _state["calls"] = 0
    _state["ok"] = 0

CATS = ["billing", "delivery", "technical", "fraud"]

KW = {
    "fraud": {"unauthorized", "fraud", "hacked", "stolen"},
    "billing": {"charged", "invoice", "bill", "refund", "deducted", "payment"},
    "technical": {"app", "crash", "login", "otp", "error", "freezes"},
    "delivery": {"arrived", "rider", "delivery", "delivered", "late"}
}

def est_tokens(text):
    return math.ceil(len((text or "").split()) * 1.3)

def _words(t):
    return set(re.findall(r"[a-z]+", (t or "").lower()))

def _resp(content=None, tool_calls=None, finish="stop", messages=()):
    prompt = sum(
        est_tokens(m.get("content") or json.dumps(m.get("tool_calls", ""), default=str))
        for m in messages
    )
    comp = est_tokens(content or json.dumps(tool_calls or "", default=str))
    msg = NS(
        role="assistant",
        content=content,
        tool_calls=[NS(**tc) for tc in (tool_calls or [])]

In [443]:
import os

path = "mock_llm.py"

print("File exists:", os.path.exists(path))

if os.path.exists(path):
    print("File size:", os.path.getsize(path), "bytes")

    with open(path, "r", encoding="utf-8") as f:
        content = f.read()

    print("\nLast 40 lines of mock_llm.py:")
    print("\n".join(content.splitlines()[-40:]))

File exists: True
File size: 6304 bytes

Last 40 lines of mock_llm.py:
        )

    if name == "calculate_refund":
        amt = data["refund_inr"]
        if amt == 0:
            return _resp("DENIED: delivery was within 45 minutes.", messages=messages)
        if amt > 1000:
            return call(
                "escalate_to_human",
                {"order_id": order["order_id"], "refund_inr": amt}
            )
        return call(
            "issue_refund",
            {"order_id": order["order_id"], "refund_inr": amt}
        )

    if name == "issue_refund":
        return _resp(f"REFUND: INR {data['refund_inr']} issued.", messages=messages)

    if name == "escalate_to_human":
        return _resp(
            "ESCALATE: refund above INR 1000 sent to a human lead.",
            messages=messages
        )

    return _resp("DENIED: unable to process.", messages=messages)

def chat(messages, tools=None):
    head = messages[0]["content"].upper()

    if "CLASSIFY" in head:
        return _classify(messages)
    if "POLICY ASSISTANT" in head:
        return _policy(messages)
    if "AGENT" in head:
        return _agent(messages, tools)

    raise ValueError(
        "first message must name one of: CLASSIFY, POLICY ASSISTANT, AGENT"
    )

**Customer Support Ticket Classification**

In [444]:
import pandas as pd
import os

tickets = pd.read_csv("data/raw/tickets.csv")

print("Total tickets:", len(tickets))
print("Columns:", tickets.columns.tolist())
print(tickets.head())

Total tickets: 164
Columns: ['ticket_id', 'customer_id', 'order_id', 'text', 'true_category']
  ticket_id customer_id    order_id  \
0     T0024       C0486  ORD-105035
1     T0073       C0080  ORD-100816
2     T0095       C1087  ORD-111156
3     T0159       C1172         NaN
4     T0080       C0910  ORD-109516

                                                text true_category
0  There is an unauthorized transaction on my car...         fraud
1  The invoice for ORD-100816 shows a wrong amoun...       billing
2  The payment page shows an error and the app fr...     technical
3                                                NaN          none
4  I was charged for order ORD-109516 that I neve...         fraud

In [445]:
import pandas as pd
import json
import time
import mock_llm
import os

tickets = pd.read_csv("data/raw/tickets.csv")

mock_llm.reset()

results = []

for _, row in tickets.iterrows():
    ticket_text = str(row["text"]) if pd.notna(row["text"]) else ""

    if not ticket_text.strip():
        results.append({
            "ticket_id": row["ticket_id"],
            "text": ticket_text,
            "true_category": row["true_category"],
            "predicted_category": "missing_text",
            "reason": "Ticket text is missing"
        })
        continue

    messages = [
        {
            "role": "system",
            "content": "CLASSIFY"
        },
        {
            "role": "user",
            "content": ticket_text
        }
    ]

    predicted = "error"
    reason = ""

    for attempt in range(3):
        try:
            response = mock_llm.chat(messages)
            answer = response.choices[0].message.content

            try:
                data = json.loads(answer)
                category = data.get("category", "invalid")

                if category in ["billing", "delivery", "technical", "fraud"]:
                    predicted = category
                    reason = data.get("reason", "")
                else:
                    predicted = "invalid"
                    reason = "Invalid category returned"

            except (json.JSONDecodeError, TypeError):
                predicted = "invalid"
                reason = "Response was not valid JSON"

            break

        except mock_llm.TransientLLMError:
            time.sleep(0.2)

    results.append({
        "ticket_id": row["ticket_id"],
        "text": ticket_text,
        "true_category": row["true_category"],
        "predicted_category": predicted,
        "reason": reason
    })

os.makedirs("outputs", exist_ok=True)

classified = pd.DataFrame(results)
classified.to_csv("outputs/classified_tickets.csv", index=False)

print("Total tickets:", len(classified))
print("\nPredicted categories:")
print(classified["predicted_category"].value_counts())
print("\nSaved: outputs/classified_tickets.csv")
print("\nSample results:")
print(classified.head())

Total tickets: 164

Predicted categories:
predicted_category
billing         58
delivery        37
technical       24
invalid         21
fraud           20
missing_text     4
Name: count, dtype: int64

Saved: outputs/classified_tickets.csv

Sample results:
  ticket_id                                               text true_category  \
0     T0024  There is an unauthorized transaction on my car...         fraud
1     T0073  The invoice for ORD-100816 shows a wrong amoun...       billing
2     T0095  The payment page shows an error and the app fr...     technical
3     T0159                                                             none
4     T0080  I was charged for order ORD-109516 that I neve...         fraud

  predicted_category                  reason
0              fraud           keyword match
1            billing           keyword match
2            billing           keyword match
3       missing_text  Ticket text is missing
4            billing           keyword match

**Classification Accuracy**

In [446]:
import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

classified = pd.read_csv("outputs/classified_tickets.csv")

# Known categories மட்டும் எடுத்துக்கொள்வோம்
valid_categories = ["billing", "delivery", "technical", "fraud"]

evaluation = classified[
    classified["true_category"].isin(valid_categories)
].copy()

print("Total valid tickets:", len(evaluation))

# எல்லா predictions-ஐயும் மதிப்பிடுவோம்.
# invalid predictions-ம் தவறான predictions-ஆகக் கணக்கிடப்படும்.
correct = (
    evaluation["true_category"] == evaluation["predicted_category"]
)

accuracy = correct.mean() * 100

print(f"\nClassification Accuracy: {accuracy:.2f}%")
print("\nCorrect predictions:", int(correct.sum()))
print("Wrong predictions:", int((~correct).sum()))

print("\nClassification Report:")
print(classification_report(
    evaluation["true_category"],
    evaluation["predicted_category"],
    labels=valid_categories,
    zero_division=0
))

Total valid tickets: 160

Classification Accuracy: 73.75%

Correct predictions: 118
Wrong predictions: 42

Classification Report:
              precision    recall  f1-score   support

     billing       0.64      0.95      0.76        39
    delivery       1.00      0.86      0.93        43
   technical       1.00      0.62      0.76        39
       fraud       1.00      0.51      0.68        39

   micro avg       0.85      0.74      0.79       160
   macro avg       0.91      0.73      0.78       160
weighted avg       0.91      0.74      0.79       160

**Privacy Protection**

In [447]:
import pandas as pd
import re
import os

# Classified tickets-ஐ load செய்கிறோம்
df = pd.read_csv("outputs/classified_tickets.csv")

def mask_sensitive_info(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Order ID hidden
    text = re.sub(
        r"ORD-\d{6}",
        "[ORDER_ID_MASKED]",
        text,
        flags=re.IGNORECASE
    )

    # Customer ID hidden
    text = re.sub(
        r"C\d{4}",
        "[CUSTOMER_ID_MASKED]",
        text,
        flags=re.IGNORECASE
    )

    # Email address hidden
    text = re.sub(
        r"\b[\w.-]+@[\w.-]+\.\w+\b",
        "[EMAIL_MASKED]",
        text
    )

    # Phone number hidden
    text = re.sub(
        r"\b\d{10}\b",
        "[PHONE_MASKED]",
        text
    )

    return text

df["protected_text"] = df["text"].apply(mask_sensitive_info)

os.makedirs("outputs", exist_ok=True)

df.to_csv(
    "outputs/privacy_protected_tickets.csv",
    index=False
)

print("Total tickets:", len(df))
print("Privacy protection completed!")
print("Saved: outputs/privacy_protected_tickets.csv")

print("\nBefore masking:")
print(df["text"].iloc[0])

print("\nAfter masking:")
print(df["protected_text"].iloc[0])

Total tickets: 164
Privacy protection completed!
Saved: outputs/privacy_protected_tickets.csv

Before masking:
There is an unauthorized transaction on my card linked to order ORD-105035. I did not place it. Call 7766326255.

After masking:
There is an unauthorized transaction on my card linked to order [ORDER_ID_MASKED]. I did not place it. Call [PHONE_MASKED].

**Policy RAG (Retrieval-Augmented Generation)**

**Load Policy Documents**

In [448]:
import os
import glob

policy_files = glob.glob("data/policies/*.txt")

policies = {}

for file_path in policy_files:
    with open(file_path, "r", encoding="utf-8") as file:
        policies[os.path.basename(file_path)] = file.read()

print("Total policy files loaded:", len(policies))
print("\nPolicy files:")

for filename in sorted(policies.keys()):
    print("-", filename)

Total policy files loaded: 5

Policy files:
- delivery_policy.txt
- escalation_policy.txt
- payment_policy.txt
- privacy_policy.txt
- refund_policy.txt

**Ask the Policy Assistant**

In [449]:
import mock_llm
import glob
import os

policy_context = ""

for file_path in sorted(glob.glob("data/policies/*.txt")):
    with open(file_path, "r", encoding="utf-8") as file:
        policy_context += (
            f"\n[{os.path.basename(file_path)}]\n"
            + file.read()
            + "\n"
        )

messages = [
    {
        "role": "system",
        "content": "You are a POLICY ASSISTANT. Answer using only the supplied policy context."
    },
    {
        "role": "user",
        "content": (
            "CONTEXT:\n"
            + policy_context
            + "\nQUESTION: My order is delayed. What is the delivery policy?"
        )
    }
]

response = mock_llm.chat(messages)

print("Question: My order is delayed. What is the delivery policy?")
print("\nAnswer:")
print(response.choices[0].message.content)

Question: My order is delayed. What is the delivery policy?

Answer:
Delivery Policy.

Refund Agent

**Order** **Data**

In [450]:
import pandas as pd
import os

orders = pd.read_csv("data/raw/orders.csv")

print("Total orders:", len(orders))
print("Columns:", orders.columns.tolist())
print(orders.head())

Total orders: 13084
Columns: ['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes']
     order_id customer_id product_id  quantity             order_ts  \
0  ORD-108250       C0792       P004         2  2025-09-01 12:24:59
1  ORD-101939       C0190       P003         1  2025-08-17 07:07:23
2  ORD-108765       C0841       P033         1  2025-07-13 09:42:32
3  ORD-108861       C0852       P010         1  2025-07-04 11:23:24
4  ORD-109150       C0877       P018         2  2025-05-07 15:35:01

      status  discount_pct order_amount  delivery_minutes
0  completed             0        310.0              17.0
1  completed             5       232.75              21.0
2  completed            10       1349.1              27.0
3  completed             0         45.0              30.0
4  completed            20         96.0              28.0

**Check Refund Eligibility**

In [451]:
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

print("Total orders:", len(orders))
print("\nOrder status counts:")
print(orders["status"].value_counts(dropna=False))

print("\nMissing values:")
print(orders[["order_id", "status", "order_amount", "delivery_minutes"]].isna().sum())

print("\nCompleted order examples:")
print(
    orders.loc[
        orders["status"].eq("completed"),
        ["order_id", "status", "order_amount", "delivery_minutes"]
    ].head(10).to_string(index=False)
)

Total orders: 13084

Order status counts:
status
completed    11217
cancelled     1211
pending        656
Name: count, dtype: int64

Missing values:
order_id               0
status                 0
order_amount          53
delivery_minutes    2541
dtype: int64

Completed order examples:
  order_id    status order_amount  delivery_minutes
ORD-108250 completed        310.0              17.0
ORD-101939 completed       232.75              21.0
ORD-108765 completed       1349.1              27.0
ORD-108861 completed         45.0              30.0
ORD-109150 completed         96.0              28.0
ORD-110648 completed        106.4              26.0
ORD-109638 completed        300.0              20.0
ORD-101535 completed         68.4              31.0
ORD-109326 completed         54.0              26.0
ORD-105250 completed        639.2              17.0

**Create Refund Tools**

In [452]:
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

def get_order(order_id):
    result = orders.loc[orders["order_id"] == order_id]

    if result.empty:
        return {"error": "Order not found"}

    row = result.iloc[0]

    return {
        "order_id": row["order_id"],
        "status": row["status"],
        "order_amount": (
            None if pd.isna(row["order_amount"])
            else float(row["order_amount"])
        ),
        "delivery_minutes": (
            None if pd.isna(row["delivery_minutes"])
            else float(row["delivery_minutes"])
        )
    }

def calculate_refund(order_amount, delivery_minutes):
    if order_amount is None or delivery_minutes is None:
        return {"error": "Missing order amount or delivery time"}

    if delivery_minutes <= 45:
        refund_amount = 0
    else:
        refund_amount = round(float(order_amount) * 0.10, 2)

    return {"refund_inr": refund_amount}

print(get_order("ORD-108250"))
print(calculate_refund(310.0, 17.0))

{'order_id': 'ORD-108250', 'status': 'completed', 'order_amount': 310.0, 'delivery_minutes': 17.0}
{'refund_inr': 0}

**Test the Refund Agent**

In [453]:
import mock_llm
import json

messages = [
    {
        "role": "system",
        "content": "You are a REFUND AGENT. Use tools to process refund requests."
    },
    {
        "role": "user",
        "content": "Please check refund eligibility for order ORD-108250"
    }
]

response = mock_llm.chat(messages)

print("Finish reason:", response.choices[0].finish_reason)

for tool_call in response.choices[0].message.tool_calls:
    print("Tool name:", tool_call.name)
    print("Arguments:", tool_call.arguments)

Finish reason: tool_calls
Tool name: get_order
Arguments: {'order_id': 'ORD-108250'}

**Connect the Order Tool**

In [454]:
import json
import mock_llm
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

messages = [
    {
        "role": "system",
        "content": "You are a REFUND AGENT. Use tools to process refund requests."
    },
    {
        "role": "user",
        "content": "Please check refund eligibility for order ORD-108250"
    }
]

response = mock_llm.chat(messages)

tool_call = response.choices[0].message.tool_calls[0]
order_id = tool_call.arguments["order_id"]

result = orders.loc[orders["order_id"] == order_id]

if result.empty:
    order_data = {"error": "Order not found"}
else:
    row = result.iloc[0]
    order_data = {
        "order_id": row["order_id"],
        "status": row["status"],
        "order_amount": None if pd.isna(row["order_amount"]) else float(row["order_amount"]),
        "delivery_minutes": None if pd.isna(row["delivery_minutes"]) else float(row["delivery_minutes"])
    }

print("Tool called:", tool_call.name)
print("Tool result:", json.dumps(order_data))

Tool called: get_order
Tool result: {"order_id": "ORD-108250", "status": "completed", "order_amount": 310.0, "delivery_minutes": 17.0}

**Connect the Policy Search Tool**

In [455]:
import os
import glob

policy_files = glob.glob("data/policies/*.txt")

def search_policy(query):
    matches = []

    query_words = set(query.lower().split())

    for file_path in policy_files:
        with open(file_path, "r", encoding="utf-8") as file:
            content = file.read()

        if any(word in content.lower() for word in query_words):
            matches.append({
                "file": os.path.basename(file_path),
                "content": content
            })

    return matches

results = search_policy("refund policy late delivery")

print("Matching policy files:", len(results))

for result in results:
    print("\nFile:", result["file"])
    print(result["content"][:500])

Matching policy files: 5

File: delivery_policy.txt
Delivery Policy. Standard delivery is promised within 30 minutes of order confirmation in all supported cities. The supported cities are Chennai, Mumbai, Bengaluru, Delhi, Hyderabad and Pune. A delivery fee of INR 25 is charged on orders below INR 199, and delivery is free on orders of INR 199 or more. During heavy rain the promised time may extend to 60 minutes and the app shows a rain notice. A rider will attempt to contact the customer twice before marking an order as undeliverable. Electroni

File: privacy_policy.txt
Privacy Policy. Customer phone numbers and email addresses are used only for order updates and support. Support tickets are processed with personal details masked before any automated tool reads them. Delivery addresses are deleted from active systems 180 days after the last order. A customer can ask for account deletion and the request is completed within 30 days. Payment card numbers are never stored by the support system.


File: refund_policy.txt
Refund Policy. A refund can be requested only for orders whose status is completed. Orders with status cancelled were never charged, so no refund applies to them. If a completed order is delivered in more than 45 minutes, the customer receives a full refund of the order amount. If a completed order is delivered in 45 minutes or less, no late-delivery refund is paid. Refunds up to INR 1000 are approved automatically by the support system. A refund above INR 1000 must be approved by a human suppor

File: escalation_policy.txt
Escalation Policy. A ticket about fraud or an unauthorized transaction is marked high priority and sent to the security team within 2 hours. Tickets from premium customers are answered within 1 hour, and all other tickets within 24 hours. If an automated assistant cannot resolve a ticket within 6 steps, it must hand the case to a human agent with a short summary. A human agent must call the customer back if such a high-value request is rejected.


File: payment_policy.txt
Payment Policy. Customers can pay using UPI, debit card, credit card or cash on delivery. Cash on delivery is available only for orders up to INR 2500. If a payment fails but money is deducted, the amount is returned automatically within 48 hours. A customer who sees two charges for one order should raise a billing ticket with the order identifier. Wallet balance can be used for any order and is never refunded as cash. Coupons cannot be combined with wallet balance on the same order.

**Test Refund Calculation Using the Actual Policy**

In [456]:
def calculate_refund(order_amount, delivery_minutes, status):
    if status != "completed":
        return {
            "refund_inr": 0,
            "decision": "DENIED",
            "reason": "Only completed orders are eligible"
        }

    if pd.isna(order_amount) or pd.isna(delivery_minutes):
        return {
            "refund_inr": 0,
            "decision": "NEEDS_REVIEW",
            "reason": "Missing order amount or delivery time"
        }

    if delivery_minutes <= 45:
        return {
            "refund_inr": 0,
            "decision": "DENIED",
            "reason": "Delivery was within 45 minutes"
        }

    refund_amount = float(order_amount)

    if refund_amount <= 1000:
        decision = "AUTO_APPROVED"
    else:
        decision = "HUMAN_APPROVAL_REQUIRED"

    return {
        "refund_inr": refund_amount,
        "decision": decision,
        "reason": "Delivery exceeded 45 minutes"
    }


print(calculate_refund(500, 60, "completed"))
print(calculate_refund(1500, 60, "completed"))
print(calculate_refund(500, 30, "completed"))
print(calculate_refund(500, 60, "cancelled"))

{'refund_inr': 500.0, 'decision': 'AUTO_APPROVED', 'reason': 'Delivery exceeded 45 minutes'}
{'refund_inr': 1500.0, 'decision': 'HUMAN_APPROVAL_REQUIRED', 'reason': 'Delivery exceeded 45 minutes'}
{'refund_inr': 0, 'decision': 'DENIED', 'reason': 'Delivery was within 45 minutes'}
{'refund_inr': 0, 'decision': 'DENIED', 'reason': 'Only completed orders are eligible'}

**Test the Refund Agent with a Real Order**

In [457]:
import pandas as pd
import mock_llm
import json

orders = pd.read_csv("data/raw/orders.csv")

# Find a completed order delivered after 45 minutes
eligible_orders = orders[
    (orders["status"] == "completed") &
    (orders["delivery_minutes"] > 45) &
    (orders["order_amount"].notna())
]

print("Eligible orders found:", len(eligible_orders))

if len(eligible_orders) > 0:
    order = eligible_orders.iloc[0]

    print("\nTest order ID:", order["order_id"])
    print("Order amount:", order["order_amount"])
    print("Delivery minutes:", order["delivery_minutes"])

    result = calculate_refund(
        order["order_amount"],
        order["delivery_minutes"],
        order["status"]
    )

    print("\nRefund decision:")
    print(result)
else:
    print("No eligible orders found.")

Eligible orders found: 983

Test order ID: ORD-110227
Order amount: 75.6
Delivery minutes: 49.0

Refund decision:
{'refund_inr': 75.6, 'decision': 'AUTO_APPROVED', 'reason': 'Delivery exceeded 45 minutes'}

**Save the Refund Test Results**

In [458]:
import pandas as pd
import os

orders = pd.read_csv("data/raw/orders.csv")

orders["order_amount"] = pd.to_numeric(
    orders["order_amount"], errors="coerce"
)

orders["delivery_minutes"] = pd.to_numeric(
    orders["delivery_minutes"], errors="coerce"
)

eligible_orders = orders[
    (orders["status"] == "completed") &
    (orders["delivery_minutes"] > 45) &
    (orders["order_amount"].notna())
].copy()

eligible_orders["refund_inr"] = eligible_orders["order_amount"]

eligible_orders["decision"] = eligible_orders["refund_inr"].apply(
    lambda amount: (
        "AUTO_APPROVED"
        if amount <= 1000
        else "HUMAN_APPROVAL_REQUIRED"
    )
)

eligible_orders["reason"] = "Delivery exceeded 45 minutes"

os.makedirs("outputs", exist_ok=True)

eligible_orders.to_csv(
    "outputs/refund_eligibility_results.csv",
    index=False
)

print("Eligible orders processed:", len(eligible_orders))
print("Results saved: outputs/refund_eligibility_results.csv")

print("\nDecision counts:")
print(eligible_orders["decision"].value_counts())

print("\nSample results:")
print(
    eligible_orders[
        ["order_id", "order_amount", "delivery_minutes",
         "refund_inr", "decision"]
    ].head()
)

Eligible orders processed: 976
Results saved: outputs/refund_eligibility_results.csv

Decision counts:
decision
AUTO_APPROVED              922
HUMAN_APPROVAL_REQUIRED     54
Name: count, dtype: int64

Sample results:
      order_id  order_amount  delivery_minutes  refund_inr       decision
30  ORD-110227          75.6              49.0        75.6  AUTO_APPROVED
36  ORD-102253         198.0              60.0       198.0  AUTO_APPROVED
37  ORD-102547          33.6              52.0        33.6  AUTO_APPROVED
51  ORD-110865         331.5              75.0       331.5  AUTO_APPROVED
56  ORD-102430         306.0              56.0       306.0  AUTO_APPROVED

**Verify Saved Output**

In [459]:
import os
import pandas as pd

file_path = "outputs/refund_eligibility_results.csv"

print("File exists:", os.path.exists(file_path))

results = pd.read_csv(file_path)

print("Total rows saved:", len(results))
print("Columns:", results.columns.tolist())
print("\nMissing values:")
print(results.isna().sum())

File exists: True
Total rows saved: 976
Columns: ['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes', 'refund_inr', 'decision', 'reason']

Missing values:
order_id            0
customer_id         0
product_id          0
quantity            0
order_ts            0
status              0
discount_pct        0
order_amount        0
delivery_minutes    0
refund_inr          0
decision            0
reason              0
dtype: int64

**Check Project Files**

In [460]:
import os

required_files = [
    "generate_data.py",
    "mock_llm.py",
    "data/raw/customers.csv",
    "data/raw/products.csv",
    "data/raw/orders.csv",
    "data/raw/tickets.csv",
    "data/raw/policy_eval.csv",
    "data/policies/delivery_policy.txt",
    "data/policies/escalation_policy.txt",
    "data/policies/payment_policy.txt",
    "data/policies/privacy_policy.txt",
    "data/policies/refund_policy.txt",
    "outputs/classified_tickets.csv",
    "outputs/privacy_protected_tickets.csv",
    "outputs/refund_eligibility_results.csv"
]

print("PROJECT FILE CHECK")
print("-" * 40)

for file_path in required_files:
    status = "FOUND" if os.path.exists(file_path) else "MISSING"
    print(f"{status}: {file_path}")

missing_files = [
    file_path for file_path in required_files
    if not os.path.exists(file_path)
]

print("\nTotal required files:", len(required_files))
print("Missing files:", len(missing_files))

PROJECT FILE CHECK
----------------------------------------
FOUND: generate_data.py
FOUND: mock_llm.py
FOUND: data/raw/customers.csv
FOUND: data/raw/products.csv
FOUND: data/raw/orders.csv
FOUND: data/raw/tickets.csv
FOUND: data/raw/policy_eval.csv
FOUND: data/policies/delivery_policy.txt
FOUND: data/policies/escalation_policy.txt
FOUND: data/policies/payment_policy.txt
FOUND: data/policies/privacy_policy.txt
FOUND: data/policies/refund_policy.txt
FOUND: outputs/classified_tickets.csv
FOUND: outputs/privacy_protected_tickets.csv
FOUND: outputs/refund_eligibility_results.csv

Total required files: 15
Missing files: 0

**Create a Project Summary**

In [461]:
import pandas as pd
import os

summary = {
    "Customers": len(pd.read_csv("data/raw/customers.csv")),
    "Products": len(pd.read_csv("data/raw/products.csv")),
    "Orders": len(pd.read_csv("data/raw/orders.csv")),
    "Support Tickets": len(pd.read_csv("data/raw/tickets.csv")),
    "Classified Tickets": len(pd.read_csv("outputs/classified_tickets.csv")),
    "Privacy Protected Tickets": len(pd.read_csv("outputs/privacy_protected_tickets.csv")),
    "Refund Results": len(pd.read_csv("outputs/refund_eligibility_results.csv"))
}

print("=" * 45)
print("INSTAMART CAPSTONE PROJECT SUMMARY")
print("=" * 45)

for name, count in summary.items():
    print(f"{name}: {count}")

print("\nPolicy Documents:", len(os.listdir("data/policies")))
print("Project Summary Generated Successfully!")

=============================================
INSTAMART CAPSTONE PROJECT SUMMARY
=============================================
Customers: 1200
Products: 40
Orders: 13084
Support Tickets: 164
Classified Tickets: 164
Privacy Protected Tickets: 164
Refund Results: 976

Policy Documents: 5
Project Summary Generated Successfully!

In [462]:
import os
import pandas as pd

print("CUSTOMER ANALYSIS FILE CHECK")
print("=" * 40)

for path in [
    "data/processed/instamart.db",
    "data/raw/customers.csv",
    "data/raw/orders.csv",
    "outputs"
]:
    print(f"{path}: {'FOUND' if os.path.exists(path) else 'NOT FOUND'}")

if os.path.exists("data/raw/customers.csv"):
    customers = pd.read_csv("data/raw/customers.csv")
    print("\nCustomer columns:")
    print(customers.columns.tolist())

if os.path.exists("data/raw/orders.csv"):
    orders = pd.read_csv("data/raw/orders.csv")
    print("\nOrder columns:")
    print(orders.columns.tolist())

CUSTOMER ANALYSIS FILE CHECK
========================================
data/processed/instamart.db: FOUND
data/raw/customers.csv: FOUND
data/raw/orders.csv: FOUND
outputs: FOUND

Customer columns:
['customer_id', 'city', 'signup_date', 'age', 'gender']

Order columns:
['order_id', 'customer_id', 'product_id', 'quantity', 'order_ts', 'status', 'discount_pct', 'order_amount', 'delivery_minutes']

**Customer Analysis**

In [463]:
import pandas as pd

customers = pd.read_csv("data/raw/customers.csv")
orders = pd.read_csv("data/raw/orders.csv")

orders["order_ts"] = pd.to_datetime(orders["order_ts"], errors="coerce")
orders["order_amount"] = pd.to_numeric(orders["order_amount"], errors="coerce")

completed = orders[orders["status"].str.lower() == "completed"].copy()

customer_summary = completed.groupby("customer_id").agg(
    completed_orders=("order_id", "count"),
    total_spend=("order_amount", "sum"),
    last_order_date=("order_ts", "max")
).reset_index()

customer_summary = customers.merge(
    customer_summary,
    on="customer_id",
    how="left"
)

customer_summary["completed_orders"] = (
    customer_summary["completed_orders"].fillna(0).astype(int)
)

customer_summary["total_spend"] = customer_summary["total_spend"].fillna(0)

print("CUSTOMER ANALYSIS")
print("=" * 40)
print("Total customers:", len(customer_summary))
print("\nCompleted orders per customer:")
print(customer_summary["completed_orders"].describe())

print("\nTotal spend per customer:")
print(customer_summary["total_spend"].describe())

print("\nLast order date available:", customer_summary["last_order_date"].max())

print("\nSample customer summary:")
print(customer_summary.head(5).to_string(index=False))

CUSTOMER ANALYSIS
========================================
Total customers: 1200

Completed orders per customer:
count    1200.000000
mean        9.347500
std         8.134405
min         0.000000
25%         3.000000
50%         5.000000
75%        17.000000
max        33.000000
Name: completed_orders, dtype: float64

Total spend per customer:
count     1200.000000
mean      2496.900333
std       2380.496315
min          0.000000
25%        471.600000
50%       2161.875000
75%       3725.712500
max      14766.550000
Name: total_spend, dtype: float64

Last order date available: 2025-09-30 22:46:26

Sample customer summary:
customer_id      city signup_date  age gender  completed_orders  total_spend     last_order_date
      C0001   Chennai  2024-01-13 35.0   MALE                 4       487.65 2025-09-16 08:07:21
      C0002     DELHI  2024-02-17 31.0   MALE                 7      4644.90 2025-09-02 13:33:13
      C0003 bengaluru  2025-02-18 18.0      F                22      3644.85 2025-09-23 16:55:36
      C0004 Bengaluru  2024-06-21 24.0 FEMALE                 5       369.00 2025-09-30 15:09:46
      C0005 Bengaluru  2024-10-01 25.0 FEMALE                 2       324.00 2025-05-06 21:44:20

**Customer Segmentation + Lapse Prediction**

In [464]:
import pandas as pd

# Prepare customer summary
customers = pd.read_csv("data/raw/customers.csv")
orders = pd.read_csv("data/raw/orders.csv")

orders["order_ts"] = pd.to_datetime(orders["order_ts"], errors="coerce")
orders["order_amount"] = pd.to_numeric(orders["order_amount"], errors="coerce")

completed = orders[orders["status"].str.lower() == "completed"].copy()

summary = completed.groupby("customer_id").agg(
    completed_orders=("order_id", "count"),
    total_spend=("order_amount", "sum"),
    last_order_date=("order_ts", "max")
).reset_index()

df = customers.merge(summary, on="customer_id", how="left")

df["completed_orders"] = df["completed_orders"].fillna(0).astype(int)
df["total_spend"] = df["total_spend"].fillna(0)

# Customer segments
def assign_segment(row):
    if row["completed_orders"] >= 15 and row["total_spend"] >= 5000:
        return "Premium"
    elif row["completed_orders"] >= 5:
        return "Frequent"
    else:
        return "Rare"

df["customer_segment"] = df.apply(assign_segment, axis=1)

# Lapse prediction using last completed order date
reference_date = orders["order_ts"].max().normalize()

df["days_since_last_order"] = (
    reference_date - df["last_order_date"].dt.normalize()
).dt.days

def assign_lapse(row):
    if pd.isna(row["last_order_date"]):
        return "No Completed Orders"
    elif row["days_since_last_order"] > 30:
        return "At Risk"
    else:
        return "Active"

df["lapse_status"] = df.apply(assign_lapse, axis=1)

# Save results
import os
os.makedirs("outputs", exist_ok=True)

output_path = "outputs/customer_segments_lapse.csv"
df.to_csv(output_path, index=False)

print("CUSTOMER SEGMENTATION RESULTS")
print("=" * 40)
print("\nCustomer Segments:")
print(df["customer_segment"].value_counts())

print("\nLapse Status:")
print(df["lapse_status"].value_counts())

print("\nSample Results:")
print(df[[
    "customer_id",
    "completed_orders",
    "total_spend",
    "customer_segment",
    "days_since_last_order",
    "lapse_status"
]].head(10).to_string(index=False))

print("\nSaved:", output_path)

CUSTOMER SEGMENTATION RESULTS
========================================

Customer Segments:
customer_segment
Frequent    641
Rare        533
Premium      26
Name: count, dtype: int64

Lapse Status:
lapse_status
Active                 743
At Risk                432
No Completed Orders     25
Name: count, dtype: int64

Sample Results:
customer_id  completed_orders  total_spend customer_segment  days_since_last_order lapse_status
      C0001                 4       487.65             Rare                   14.0       Active
      C0002                 7      4644.90         Frequent                   28.0       Active
      C0003                22      3644.85         Frequent                    7.0       Active
      C0004                 5       369.00         Frequent                    0.0       Active
      C0005                 2       324.00             Rare                  147.0      At Risk
      C0006                 1        90.00             Rare                   34.0      At Risk
      C0007                19      2894.50         Frequent                    3.0       Active
      C0008                15      3096.50         Frequent                    3.0       Active
      C0009                11      8424.80         Frequent                   19.0       Active
      C0010                 4       450.00             Rare                   66.0      At Risk

Saved: outputs/customer_segments_lapse.csv

**Policy RAG Evaluation**

In [465]:
import pandas as pd
import os

print("POLICY EVALUATION FILE CHECK")
print("=" * 40)

path = "data/raw/policy_eval.csv"

if os.path.exists(path):
    policy_eval = pd.read_csv(path)

    print("Rows:", len(policy_eval))
    print("Columns:", policy_eval.columns.tolist())
    print("\nFirst 5 rows:")
    print(policy_eval.head().to_string(index=False))
else:
    print("Policy evaluation file not found.")

POLICY EVALUATION FILE CHECK
========================================
Rows: 14
Columns: ['question', 'expected_doc', 'expected_fact']

First 5 rows:
                                                              question        expected_doc        expected_fact
What delivery time makes a completed order eligible for a full refund?   refund_policy.txt more than 45 minutes
                             Who must approve a refund above INR 1000?   refund_policy.txt   human support lead
                    How many days do I have to raise a refund request?   refund_policy.txt        within 7 days
                             What is the delivery fee on small orders? delivery_policy.txt               INR 25
                             On orders of what value is delivery free? delivery_policy.txt      INR 199 or more

**Policy RAG Evaluation**

In [466]:
import os
import pandas as pd

eval_df = pd.read_csv("data/raw/policy_eval.csv")
policy_dir = "data/policies"

results = []

for _, row in eval_df.iterrows():
    doc_path = os.path.join(policy_dir, row["expected_doc"])

    if os.path.exists(doc_path):
        with open(doc_path, "r", encoding="utf-8") as file:
            policy_text = file.read().lower()

        fact = str(row["expected_fact"]).lower()
        found = fact in policy_text

        results.append({
            "question": row["question"],
            "expected_doc": row["expected_doc"],
            "expected_fact": row["expected_fact"],
            "fact_found": found
        })
    else:
        results.append({
            "question": row["question"],
            "expected_doc": row["expected_doc"],
            "expected_fact": row["expected_fact"],
            "fact_found": False
        })

results_df = pd.DataFrame(results)

os.makedirs("outputs", exist_ok=True)
results_df.to_csv("outputs/policy_evaluation_results.csv", index=False)

print("POLICY EVALUATION RESULTS")
print("=" * 40)
print(results_df[[
    "expected_doc",
    "expected_fact",
    "fact_found"
]].to_string(index=False))

print("\nTotal questions:", len(results_df))
print("Facts found:", int(results_df["fact_found"].sum()))
print("Facts not found:", int((~results_df["fact_found"]).sum()))

accuracy = results_df["fact_found"].mean() * 100
print(f"Exact fact-match rate: {accuracy:.2f}%")
print("\nSaved: outputs/policy_evaluation_results.csv")

POLICY EVALUATION RESULTS
========================================
         expected_doc          expected_fact  fact_found
    refund_policy.txt   more than 45 minutes        True
    refund_policy.txt     human support lead        True
    refund_policy.txt          within 7 days        True
  delivery_policy.txt                 INR 25        True
  delivery_policy.txt        INR 199 or more        True
  delivery_policy.txt      one time password        True
   payment_policy.txt               INR 2500        True
   payment_policy.txt               48 hours        True
   payment_policy.txt never refunded as cash        True
   privacy_policy.txt               180 days        True
escalation_policy.txt         within 2 hours        True
escalation_policy.txt                6 steps        True
                 NONE                    NaN       False
                 NONE                    NaN       False

Total questions: 14
Facts found: 12
Facts not found: 2
Exact fact-match rate: 85.71%

Saved: outputs/policy_evaluation_results.csv

In [467]:
import pandas as pd

eval_df = pd.read_csv("data/raw/policy_eval.csv")

print("QUESTIONS NEEDING REVIEW")
print("=" * 40)

print(
    eval_df[eval_df["expected_doc"].isna() |
            (eval_df["expected_doc"].astype(str).str.upper() == "NONE")]
    .to_string(index=False)
)

QUESTIONS NEEDING REVIEW
========================================
                                           question expected_doc expected_fact
What is the favourite colour of the company mascot?         NONE           NaN
               Who won the cricket world cup final?         NONE           NaN

In [468]:
import pandas as pd

eval_df = pd.read_csv("data/raw/policy_eval.csv")

valid_policy_questions = eval_df[
    eval_df["expected_doc"].notna()
    & (eval_df["expected_doc"].astype(str).str.upper() != "NONE")
]

unanswerable_questions = eval_df[
    eval_df["expected_doc"].isna()
    | (eval_df["expected_doc"].astype(str).str.upper() == "NONE")
]

print("POLICY EVALUATION SUMMARY")
print("=" * 40)
print("Total questions:", len(eval_df))
print("Questions with expected policy facts:", len(valid_policy_questions))
print("Unanswerable questions:", len(unanswerable_questions))

print("\nUnanswerable questions:")
for question in unanswerable_questions["question"]:
    print("-", question)

print("\nExpected behavior:")
print("The assistant should state that the information is not available")
print("in the supplied policy documents.")

POLICY EVALUATION SUMMARY
========================================
Total questions: 14
Questions with expected policy facts: 12
Unanswerable questions: 2

Unanswerable questions:
- What is the favourite colour of the company mascot?
- Who won the cricket world cup final?

Expected behavior:
The assistant should state that the information is not available
in the supplied policy documents.

**Policy Assistant Test**

In [469]:
import os
import mock_llm

policy_dir = "data/policies"
policy_context = ""

for filename in sorted(os.listdir(policy_dir)):
    if filename.endswith(".txt"):
        path = os.path.join(policy_dir, filename)
        with open(path, "r", encoding="utf-8") as file:
            policy_context += f"\n[{filename}]\n{file.read()}\n"

test_questions = [
    "What delivery time makes a completed order eligible for a full refund?",
    "Who must approve a refund above INR 1000?",
    "What is the favourite colour of the company mascot?",
    "Who won the cricket world cup final?"
]

print("POLICY ASSISTANT TEST")
print("=" * 50)

for question in test_questions:
    messages = [
        {
            "role": "system",
            "content": "You are a POLICY ASSISTANT. Answer only using the supplied policy context."
        },
        {
            "role": "user",
            "content": (
                f"CONTEXT:\n{policy_context}\n"
                f"QUESTION:\n{question}"
            )
        }
    ]

    response = mock_llm.chat(messages)
    answer = response.choices[0].message.content

    print("\nQuestion:", question)
    print("Answer:", answer)

POLICY ASSISTANT TEST
==================================================

Question: What delivery time makes a completed order eligible for a full refund?
Answer: If a completed order is delivered in more than 45 minutes, the customer receives a full refund of the order amount.

Question: Who must approve a refund above INR 1000?
Answer: A refund above INR 1000 must be approved by a human support lead before money is returned.

Question: What is the favourite colour of the company mascot?
Answer: I could not find that information in the policy documents.

Question: Who won the cricket world cup final?
Answer: I could not find that information in the policy documents.

In [470]:
import pandas as pd
import mock_llm

orders = pd.read_csv("data/raw/orders.csv")

print("REFUND AGENT PRE-CHECK")
print("=" * 40)

print("Mock LLM imported:", hasattr(mock_llm, "chat"))
print("Orders loaded:", len(orders))
print("Required columns available:")

required_columns = [
    "order_id",
    "customer_id",
    "status",
    "order_amount",
    "delivery_minutes"
]

for column in required_columns:
    print(f"{column}: {column in orders.columns}")

print("\nSample completed orders:")
print(
    orders.loc[
        orders["status"].str.lower() == "completed",
        ["order_id", "status", "order_amount", "delivery_minutes"]
    ].head(5).to_string(index=False)
)

REFUND AGENT PRE-CHECK
========================================
Mock LLM imported: True
Orders loaded: 13084
Required columns available:
order_id: True
customer_id: True
status: True
order_amount: True
delivery_minutes: True

Sample completed orders:
  order_id    status order_amount  delivery_minutes
ORD-108250 completed        310.0              17.0
ORD-101939 completed       232.75              21.0
ORD-108765 completed       1349.1              27.0
ORD-108861 completed         45.0              30.0
ORD-109150 completed         96.0              28.0

**Refund Agent Functions**

In [471]:
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

orders["order_amount"] = pd.to_numeric(
    orders["order_amount"], errors="coerce"
)
orders["delivery_minutes"] = pd.to_numeric(
    orders["delivery_minutes"], errors="coerce"
)

def get_order(order_id):
    match = orders[orders["order_id"] == order_id]

    if match.empty:
        return {"error": "Order not found"}

    order = match.iloc[0]

    return {
        "order_id": order["order_id"],
        "customer_id": order["customer_id"],
        "status": str(order["status"]).lower(),
        "order_amount": order["order_amount"],
        "delivery_minutes": order["delivery_minutes"]
    }

def calculate_refund(order):
    if order.get("error"):
        return {
            "decision": "NOT_FOUND",
            "refund_inr": 0,
            "reason": "Order not found"
        }

    if order["status"] != "completed":
        return {
            "decision": "DENIED",
            "refund_inr": 0,
            "reason": "Only completed orders are eligible"
        }

    if pd.isna(order["order_amount"]) or pd.isna(order["delivery_minutes"]):
        return {
            "decision": "NEEDS_REVIEW",
            "refund_inr": 0,
            "reason": "Order amount or delivery time is missing"
        }

    if order["delivery_minutes"] <= 45:
        return {
            "decision": "DENIED",
            "refund_inr": 0,
            "reason": "Delivery was within 45 minutes"
        }

    amount = float(order["order_amount"])

    if amount <= 1000:
        decision = "AUTO_APPROVED"
        reason = "Eligible under the refund policy"
    else:
        decision = "HUMAN_APPROVAL_REQUIRED"
        reason = "Refund exceeds INR 1000"

    return {
        "decision": decision,
        "refund_inr": round(amount, 2),
        "reason": reason
    }

# Test with one existing order
test_order_id = "ORD-108250"

order = get_order(test_order_id)
refund = calculate_refund(order)

print("ORDER LOOKUP")
print(order)

print("\nREFUND DECISION")
print(refund)

ORDER LOOKUP
{'order_id': 'ORD-108250', 'customer_id': 'C0792', 'status': 'completed', 'order_amount': np.float64(310.0), 'delivery_minutes': np.float64(17.0)}

REFUND DECISION
{'decision': 'DENIED', 'refund_inr': 0, 'reason': 'Delivery was within 45 minutes'}

**Refund Agent Tool Calls**

In [472]:
import json
import mock_llm

messages = [
    {
        "role": "system",
        "content": "You are an AGENT that follows the refund policy."
    },
    {
        "role": "user",
        "content": "Check refund eligibility for order ORD-108250"
    }
]

response = mock_llm.chat(messages, tools=[])

print("FINISH REASON:", response.choices[0].finish_reason)

message = response.choices[0].message

print("\nASSISTANT MESSAGE:", message.content)
print("\nTOOL CALLS:")

for tool_call in message.tool_calls:
    print("Tool name:", tool_call.name)
    print("Arguments:", tool_call.arguments)

FINISH REASON: tool_calls

ASSISTANT MESSAGE: None

TOOL CALLS:
Tool name: get_order
Arguments: {'order_id': 'ORD-108250'}

**Agent Tool Execution**

In [473]:
import json
import mock_llm
import pandas as pd

orders = pd.read_csv("data/raw/orders.csv")

def get_order_tool(order_id):
    match = orders[orders["order_id"] == order_id]

    if match.empty:
        return {"error": "Order not found"}

    row = match.iloc[0]

    return {
        "order_id": str(row["order_id"]),
        "customer_id": str(row["customer_id"]),
        "status": str(row["status"]).lower(),
        "order_amount": None if pd.isna(row["order_amount"]) else float(row["order_amount"]),
        "delivery_minutes": None if pd.isna(row["delivery_minutes"]) else float(row["delivery_minutes"])
    }

order_id = "ORD-108250"
order_data = get_order_tool(order_id)

messages = [
    {
        "role": "system",
        "content": "You are an AGENT that follows the refund policy."
    },
    {
        "role": "user",
        "content": f"Check refund eligibility for order {order_id}"
    },
    {
        "role": "assistant",
        "content": None,
        "tool_calls": [
            {
                "id": "call_1",
                "type": "function",
                "function": {
                    "name": "get_order",
                    "arguments": json.dumps({"order_id": order_id})
                }
            }
        ]
    },
    {
        "role": "tool",
        "tool_call_id": "call_1",
        "name": "get_order",
        "content": json.dumps(order_data)
    }
]

response = mock_llm.chat(messages, tools=[])

print("ORDER DATA:")
print(json.dumps(order_data, indent=2))

print("\nNEXT AGENT RESPONSE:")
print("Finish reason:", response.choices[0].finish_reason)
print("Message:", response.choices[0].message.content)

for tool_call in response.choices[0].message.tool_calls:
    print("Next tool:", tool_call.name)
    print("Arguments:", tool_call.arguments)

ORDER DATA:
{
  "order_id": "ORD-108250",
  "customer_id": "C0792",
  "status": "completed",
  "order_amount": 310.0,
  "delivery_minutes": 17.0
}

NEXT AGENT RESPONSE:
Finish reason: tool_calls
Message: None
Next tool: search_policy
Arguments: {'query': 'refund policy late delivery'}

**Policy Search Tool**

In [474]:
import os
import json

policy_dir = "data/policies"

def search_policy_tool(query):
    matches = []

    for filename in sorted(os.listdir(policy_dir)):
        if filename.endswith(".txt"):
            path = os.path.join(policy_dir, filename)

            with open(path, "r", encoding="utf-8") as file:
                content = file.read()

            if "refund" in filename.lower() or "refund" in query.lower():
                matches.append({
                    "document": filename,
                    "content": content
                })

    return matches

policy_results = search_policy_tool("refund policy late delivery")

print("POLICY SEARCH RESULTS")
print("=" * 40)

for item in policy_results:
    print("\nDocument:", item["document"])
    print(item["content"][:800])

print("\nDocuments found:", len(policy_results))

POLICY SEARCH RESULTS
========================================

Document: delivery_policy.txt
Delivery Policy. Standard delivery is promised within 30 minutes of order confirmation in all supported cities. The supported cities are Chennai, Mumbai, Bengaluru, Delhi, Hyderabad and Pune. A delivery fee of INR 25 is charged on orders below INR 199, and delivery is free on orders of INR 199 or more. During heavy rain the promised time may extend to 60 minutes and the app shows a rain notice. A rider will attempt to contact the customer twice before marking an order as undeliverable. Electronics items are delivered only after the customer shares a one time password with the rider.


Document: escalation_policy.txt
Escalation Policy. A ticket about fraud or an unauthorized transaction is marked high priority and sent to the security team within 2 hours. Tickets from premium customers are answered within 1 hour, and all other tickets within 24 hours. If an automated assistant cannot resolve a ticket within 6 steps, it must hand the case to a human agent with a short summary. A human agent must call the customer back if such a high-value request is rejected.


Document: payment_policy.txt
Payment Policy. Customers can pay using UPI, debit card, credit card or cash on delivery. Cash on delivery is available only for orders up to INR 2500. If a payment fails but money is deducted, the amount is returned automatically within 48 hours. A customer who sees two charges for one order should raise a billing ticket with the order identifier. Wallet balance can be used for any order and is never refunded as cash. Coupons cannot be combined with wallet balance on the same order.


Document: privacy_policy.txt
Privacy Policy. Customer phone numbers and email addresses are used only for order updates and support. Support tickets are processed with personal details masked before any automated tool reads them. Delivery addresses are deleted from active systems 180 days after the last order. A customer can ask for account deletion and the request is completed within 30 days. Payment card numbers are never stored by the support system.


Document: refund_policy.txt
Refund Policy. A refund can be requested only for orders whose status is completed. Orders with status cancelled were never charged, so no refund applies to them. If a completed order is delivered in more than 45 minutes, the customer receives a full refund of the order amount. If a completed order is delivered in 45 minutes or less, no late-delivery refund is paid. Refunds up to INR 1000 are approved automatically by the support system. A refund above INR 1000 must be approved by a human support lead before money is returned. Approved refunds are credited to the original payment method within 5 working days. A refund request must be raised within 7 days of the delivery date.


Documents found: 5

**Integrated Refund Agent**

In [475]:
import pandas as pd
import json
import os
import mock_llm

orders = pd.read_csv("data/raw/orders.csv")

orders["order_amount"] = pd.to_numeric(
    orders["order_amount"], errors="coerce"
)
orders["delivery_minutes"] = pd.to_numeric(
    orders["delivery_minutes"], errors="coerce"
)

def get_order(order_id):
    match = orders[orders["order_id"] == order_id]

    if match.empty:
        return {"error": "Order not found"}

    row = match.iloc[0]

    return {
        "order_id": str(row["order_id"]),
        "customer_id": str(row["customer_id"]),
        "status": str(row["status"]).lower(),
        "order_amount": (
            None if pd.isna(row["order_amount"])
            else float(row["order_amount"])
        ),
        "delivery_minutes": (
            None if pd.isna(row["delivery_minutes"])
            else float(row["delivery_minutes"])
        )
    }

def search_refund_policy():
    path = "data/policies/refund_policy.txt"

    with open(path, "r", encoding="utf-8") as file:
        return file.read()

def process_refund(order_id):
    order = get_order(order_id)

    if "error" in order:
        return {
            "order_id": order_id,
            "decision": "NOT_FOUND",
            "refund_inr": 0,
            "reason": order["error"]
        }

    if order["status"] != "completed":
        decision = "DENIED"
        amount = 0
        reason = "Only completed orders are eligible"

    elif (
        order["order_amount"] is None
        or order["delivery_minutes"] is None
    ):
        decision = "NEEDS_REVIEW"
        amount = 0
        reason = "Order amount or delivery time is missing"

    elif order["delivery_minutes"] <= 45:
        decision = "DENIED"
        amount = 0
        reason = "Delivery was within 45 minutes"

    elif order["order_amount"] > 1000:
        decision = "HUMAN_APPROVAL_REQUIRED"
        amount = order["order_amount"]
        reason = "Refund exceeds INR 1000"

    else:
        decision = "AUTO_APPROVED"
        amount = order["order_amount"]
        reason = "Eligible under the refund policy"

    return {
        "order_id": order_id,
        "customer_id": order["customer_id"],
        "status": order["status"],
        "delivery_minutes": order["delivery_minutes"],
        "decision": decision,
        "refund_inr": round(float(amount), 2),
        "reason": reason
    }

# Run test cases
test_ids = [
    "ORD-108250",
    "INVALID-ORDER"
]

results = []

for order_id in test_ids:
    result = process_refund(order_id)
    results.append(result)
    print(json.dumps(result, indent=2))

os.makedirs("outputs", exist_ok=True)

pd.DataFrame(results).to_csv(
    "outputs/refund_agent_test_results.csv",
    index=False
)

print("\nSaved: outputs/refund_agent_test_results.csv")
print("\nRefund policy loaded:", bool(search_refund_policy()))
print("Mock LLM available:", hasattr(mock_llm, "chat"))

{
  "order_id": "ORD-108250",
  "customer_id": "C0792",
  "status": "completed",
  "delivery_minutes": 17.0,
  "decision": "DENIED",
  "refund_inr": 0.0,
  "reason": "Delivery was within 45 minutes"
}
{
  "order_id": "INVALID-ORDER",
  "decision": "NOT_FOUND",
  "refund_inr": 0,
  "reason": "Order not found"
}

Saved: outputs/refund_agent_test_results.csv

Refund policy loaded: True
Mock LLM available: True

**Database Tables correction**

In [476]:
import sqlite3

db_path = "data/processed/instamart.db"

connection = sqlite3.connect(db_path)

tables = pd.read_sql_query(
    "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name",
    connection
)

print("DATABASE TABLES")
print("=" * 40)
print(tables.to_string(index=False))

for table_name in tables["name"]:
    count = pd.read_sql_query(
        f'SELECT COUNT(*) AS total FROM "{table_name}"',
        connection
    ).iloc[0]["total"]

    print(f"{table_name}: {count} rows")

connection.close()

DATABASE TABLES
========================================
     name
customers
   orders
 products
  tickets
customers: 1200 rows
orders: 12309 rows
products: 40 rows
tickets: 164 rows

**Orders count verify**

In [477]:
import pandas as pd
import sqlite3

csv_orders = pd.read_csv("data/raw/orders.csv")
connection = sqlite3.connect("data/processed/instamart.db")

db_orders = pd.read_sql_query(
    "SELECT COUNT(*) AS total FROM orders",
    connection
).iloc[0]["total"]

print("Orders CSV count:", len(csv_orders))
print("Orders database count:", db_orders)
print("Difference:", len(csv_orders) - db_orders)

connection.close()

Orders CSV count: 13084
Orders database count: 12309
Difference: 775

In [478]:
import pandas as pd
import sqlite3

csv_orders = pd.read_csv("data/raw/orders.csv")
connection = sqlite3.connect("data/processed/instamart.db")

db_orders = pd.read_sql_query(
    "SELECT COUNT(*) AS total FROM orders",
    connection
).iloc[0]["total"]

print("CSV file orders:", len(csv_orders))
print("Database orders:", db_orders)
print("Difference:", len(csv_orders) - db_orders)

connection.close()

CSV file orders: 13084
Database orders: 12309
Difference: 775

In [479]:
import pandas as pd
import sqlite3

csv_orders = pd.read_csv("data/raw/orders.csv")
connection = sqlite3.connect("data/processed/instamart.db")

db_order_ids = pd.read_sql_query(
    "SELECT order_id FROM orders",
    connection
)["order_id"]

missing_orders = csv_orders[
    ~csv_orders["order_id"].isin(db_order_ids)
]

print("Missing orders:", len(missing_orders))
print("\nMissing orders sample:")
print(missing_orders.head(10).to_string(index=False))

connection.close()

Missing orders: 0

Missing orders sample:
Empty DataFrame
Columns: [order_id, customer_id, product_id, quantity, order_ts, status, discount_pct, order_amount, delivery_minutes]
Index: []

In [480]:
import pandas as pd
import sqlite3

csv_orders = pd.read_csv("data/raw/orders.csv")

connection = sqlite3.connect("data/processed/instamart.db")

db_orders = pd.read_sql_query(
    "SELECT order_id FROM orders",
    connection
)

print("CSV total rows:", len(csv_orders))
print("CSV unique order IDs:", csv_orders["order_id"].nunique())
print("CSV duplicate order IDs:", csv_orders["order_id"].duplicated().sum())

print("\nDatabase total rows:", len(db_orders))
print("Database unique order IDs:", db_orders["order_id"].nunique())

connection.close()

CSV total rows: 13084
CSV unique order IDs: 12309
CSV duplicate order IDs: 775

Database total rows: 12309
Database unique order IDs: 12309

In [481]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("data/processed/instamart.db")

duplicates = pd.read_sql_query("""
    SELECT order_id, COUNT(*) AS count
    FROM orders
    GROUP BY order_id
    HAVING COUNT(*) > 1
""", connection)

print("Duplicate order IDs in database:", len(duplicates))

connection.close()

Duplicate order IDs in database: 0

In [482]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("data/processed/instamart.db")

query = """
SELECT
    c.city,
    COUNT(o.order_id) AS total_orders
FROM customers AS c
LEFT JOIN orders AS o
    ON c.customer_id = o.customer_id
GROUP BY c.city
ORDER BY total_orders DESC;
"""

city_orders = pd.read_sql_query(query, connection)

print(city_orders.to_string(index=False))

connection.close()

     city  total_orders
    Delhi          2266
     Pune          2208
Bengaluru          2096
Hyderabad          2052
  Chennai          1890
   Mumbai          1797

In [483]:
import sqlite3
import pandas as pd

connection = sqlite3.connect("data/processed/instamart.db")

query = """
SELECT
    status,
    COUNT(*) AS total_orders
FROM orders
GROUP BY status
ORDER BY total_orders DESC;
"""

status_summary = pd.read_sql_query(query, connection)

print(status_summary.to_string(index=False))

connection.close()

   status  total_orders
completed         11110
cancelled          1199

In [484]:
import os

print("File exists:", os.path.exists("data/raw/agent_scenarios.csv"))
print("Raw folder exists:", os.path.exists("data/raw"))

File exists: True
Raw folder exists: True

In [485]:
import pandas as pd
import os

os.makedirs("outputs", exist_ok=True)

scenarios = pd.read_csv("data/raw/agent_scenarios.csv")

print("Total test scenarios:", len(scenarios))
print("\nExpected outcomes:")
print(scenarios["expected_outcome"].value_counts().to_string())

print("\nTest scenarios loaded successfully!")

Total test scenarios: 7

Expected outcomes:
expected_outcome
REFUND       2
DENIED       2
ESCALATE     1
NOT_FOUND    1
FALLBACK     1

Test scenarios loaded successfully!

In [486]:
import pandas as pd
import sqlite3
import os

db_path = "data/processed/instamart.db"
scenarios_path = "data/raw/agent_scenarios.csv"

connection = sqlite3.connect(db_path)

orders = pd.read_sql_query("SELECT * FROM orders", connection)
connection.close()

scenarios = pd.read_csv(scenarios_path)

print("Orders loaded:", len(orders))
print("Test scenarios loaded:", len(scenarios))
print("\nAgent setup check completed.")
print("\nExpected outcomes:")
print(scenarios["expected_outcome"].value_counts().to_string())

Orders loaded: 12309
Test scenarios loaded: 7

Agent setup check completed.

Expected outcomes:
expected_outcome
REFUND       2
DENIED       2
ESCALATE     1
NOT_FOUND    1
FALLBACK     1

In [487]:
import pandas as pd
import sqlite3
import os
import json
import mock_llm

os.makedirs("outputs", exist_ok=True)

scenarios = pd.read_csv("data/raw/agent_scenarios.csv")
connection = sqlite3.connect("data/processed/instamart.db")
orders = pd.read_sql_query("SELECT * FROM orders", connection)
connection.close()

orders["order_id"] = orders["order_id"].astype(str)
order_lookup = orders.drop_duplicates("order_id").set_index("order_id").to_dict("index")

def run_refund_test(row):
    message = str(row["message"])
    expected = row["expected_outcome"]

    if "[LOOP]" in message:
        actual = "FALLBACK"
        refund = 0.0
        reason = "Loop detected; safe fallback"
    else:
        import re
        match = re.search(r"ORD-\d{6}", message)

        if not match or match.group(0) not in order_lookup:
            actual = "NOT_FOUND"
            refund = 0.0
            reason = "Order not found"
        else:
            order = order_lookup[match.group(0)]
            status = str(order["status"]).lower()

            try:
                amount = float(order["order_amount"])
                delivery = float(order["delivery_minutes"])
            except (TypeError, ValueError):
                amount, delivery = None, None

            if status != "completed":
                actual, refund = "DENIED", 0.0
                reason = "Order is not completed"
            elif amount is None or delivery is None:
                actual, refund = "NEEDS_REVIEW", 0.0
                reason = "Missing or invalid order values"
            elif delivery <= 45:
                actual, refund = "DENIED", 0.0
                reason = "Delivery was within 45 minutes"
            elif amount > 1000:
                actual, refund = "ESCALATE", amount
                reason = "Refund above INR 1000 needs human approval"
            else:
                actual, refund = "REFUND", amount
                reason = "Eligible late delivery refund"

    return {
        "scenario_id": row["scenario_id"],
        "expected_outcome": expected,
        "actual_outcome": actual,
        "expected_refund_inr": float(row["expected_refund_inr"]),
        "actual_refund_inr": refund,
        "passed": actual == expected,
        "reason": reason
    }

results = pd.DataFrame(
    [run_refund_test(row) for _, row in scenarios.iterrows()]
)

results.to_csv("outputs/refund_agent_test_results.csv", index=False)

print(results.to_string(index=False))
print("\nPassed:", int(results["passed"].sum()), "/", len(results))
print("Saved: outputs/refund_agent_test_results.csv")

scenario_id expected_outcome actual_outcome  expected_refund_inr  actual_refund_inr  passed                                     reason
         S1           REFUND         REFUND               128.25             128.25    True              Eligible late delivery refund
         S2           REFUND         REFUND               135.00             135.00    True              Eligible late delivery refund
         S3         ESCALATE       ESCALATE              1999.00            1999.00    True Refund above INR 1000 needs human approval
         S4           DENIED         DENIED                 0.00               0.00    True             Delivery was within 45 minutes
         S5           DENIED         DENIED                 0.00               0.00    True                     Order is not completed
         S6        NOT_FOUND      NOT_FOUND                 0.00               0.00    True                            Order not found
         S7         FALLBACK       FALLBACK                 0.00               0.00    True               Loop detected; safe fallback

Passed: 7 / 7
Saved: outputs/refund_agent_test_results.csv

In [489]:
readme_content = """# Instamart Customer Intelligence & Support Copilot

## Project Overview
This project analyzes synthetic Instamart customer, order, product, and support ticket data. It demonstrates customer segmentation, ticket classification, privacy masking, policy retrieval, and refund eligibility testing.

## Tools Used
- Python
- Pandas
- SQLite
- Regular Expressions
- Mock LLM for offline testing
- Google Colab

## Main Components
1. Data cleaning and validation
2. SQLite database creation and SQL analysis
3. Customer segmentation and lapse analysis
4. Support ticket classification
5. Privacy masking
6. Policy question answering
7. Refund eligibility rules
8. Refund agent scenario testing

## Key Results
- 1,200 customers
- 40 products
- 12,309 unique order IDs in the cleaned database
- 164 support tickets
- 7 refund agent scenarios tested
- 7 of 7 scenarios passed the implemented rule-based tests

## Output Files
- customer_segments_lapse.csv
- classified_tickets.csv
- privacy_protected_tickets.csv
- refund_eligibility_results.csv
- refund_agent_test_results.csv

## Limitations
- The data is synthetic and fictional.
- Customer lapse analysis uses rule-based conditions.
- Refund agent scenario tests validate implemented rules and do not represent real payments.
- Refund request timing within the policy's seven-day window requires separate validation.
- Privacy masking uses patterns and does not guarantee complete anonymization.
- The mock LLM is an offline simulation, not a hosted language model.

## How to Run
Run the notebook cells in order in Google Colab. Ensure the required data files and policy documents are available before running the analysis.
"""

with open("README.md", "w", encoding="utf-8") as file:
    file.write(readme_content)

print("README.md created successfully!")

README.md created successfully!